import { useMemo, useState } from 'react';
import type { CompanySummary } from '../../platform/domain/AccessContext';
import type { EngineeringOverview } from '../domain/overview';
import { Button } from '../../../shared/ui/Button';
import { Card } from '../../../shared/ui/Card';
import { Dialog } from '../../../shared/ui/Dialog';
import { EmptyState, Feedback, LoadingState } from '../../../shared/ui/Feedback';
import { Input } from '../../../shared/ui/Input';
import { Select } from '../../../shared/ui/Select';
import { Tabs } from '../../../shared/ui/Tabs';
import { useEngineeringOperations } from './useEngineeringOperations';
import { useEngineeringOverview } from './useEngineeringOverview';
import './engineering.css';

interface EngineeringPageProps { company: CompanySummary; }
type ModalKind = 'contract'|'contractStatus'|'service'|'contractService'|'provisional'|'provisionalLine'|'convertProvisional'|'addendum'|'measurement'|'measurementLine'|'retention'|'measurementStatus'|'receivable'|'receive'|'productionPeriod'|'productionEntry'|'productionStatus'|null;
const currency = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
function today(){ return new Date().toISOString().slice(0,10); }
function currentMonth(){ return new Date().toISOString().slice(0,7); }
function num(value:string){ const parsed=Number(value.replace(',','.')); return Number.isFinite(parsed)?parsed:0; }

export function EngineeringPage({company}:EngineeringPageProps) {
  const [activeTab,setActiveTab]=useState('contratos');
  const [modal,setModal]=useState<ModalKind>(null);
  const [form,setForm]=useState<Record<string,string>>({});
  const [refreshToken,setRefreshToken]=useState(0);
  const scope=useMemo(()=>({tenantId:company.tenantId,companyId:company.id}),[company.id,company.tenantId]);
  const overview=useEngineeringOverview(scope,refreshToken);
  const operations=useEngineeringOperations(scope);
  const operational=operations.state.data;
  const tabs=useMemo(()=>[
    {id:'contratos',label:'Contratos'},{id:'medicoes',label:'Medições'},{id:'producao',label:'Produção'},{id:'aditivos',label:'Aditivos'},{id:'provisorios',label:'Provisórios'},
  ],[]);

  if(overview.status==='idle'||overview.status==='loading') return <LoadingState label="Carregando Engenharia…"/>;
  if(overview.status==='error') return <EmptyState title="Engenharia indisponível" message={overview.errorMessage}/>;
  if(overview.status!=='ready') return <EmptyState title="Engenharia indisponível" message="Não foi possível carregar os dados da Engenharia."/>;

  const data:EngineeringOverview=overview.data;
  const empty=<p className="ui-muted">Nenhum registro nesta empresa.</p>;
  const option=(items:readonly {id:string;name:string}[],placeholder='Selecione…')=>[{value:'',label:placeholder},...items.map(item=>({value:item.id,label:item.name}))];
  const workOptions=option(operational?.works??[]);
  const serviceOptions=option((operational?.services??[]).map(item=>({id:item.id,name:`${item.name} · ${item.unit}`})));
  const contractOptions=option((operational?.contracts??[]).map(item=>({id:item.id,name:`${item.contractNumber} · ${item.status}`})));
  const provisionalOptions=option((operational?.provisionals??[]).filter(item=>item.status!=='converted'&&item.status!=='cancelled').map(item=>({id:item.id,name:`${item.number} · ${item.status}`})));
  const measurementOptions=option((operational?.measurements??[]).map(item=>({id:item.id,name:`${item.competence.slice(0,7)} · ${item.status}`})));
  const periodOptions=option((operational?.productionPeriods??[]).map(item=>({id:item.id,name:`${item.competence.slice(0,7)} · ${item.status}`})));
  const employeeOptions=option(operational?.employees??[]);
  const accountOptions=option(operational?.accounts??[]);
  const selectedContract=form.contractId??'';
  const contractServiceOptions=option((operational?.contractServices??[]).filter(item=>!selectedContract||item.contractId===selectedContract).map(item=>({id:item.id,name:`${item.description} · ${currency.format(item.unitPrice)}/${item.unit}`})));
  const selectedPeriod=operational?.productionPeriods.find(item=>item.id===form.periodId);
  const structureOptions=option((operational?.structures??[]).filter(item=>!selectedPeriod||item.workId===selectedPeriod.workId));

  function field(name:string,value:string){ setForm(current=>({...current,[name]:value})); }
  function open(kind:Exclude<ModalKind,null>,initial:Record<string,string>={}){
    operations.clearFeedback();
    const defaults:Record<Exclude<ModalKind,null>,Record<string,string>>={
      contract:{workId:'',contractNumber:'',clientName:'',signedAt:'',startDate:'',endDate:'',notes:''},
      contractStatus:{contractId:'',status:'active'},
      service:{name:'',unit:'un',code:'',category:'',notes:''},
      contractService:{contractId:'',serviceId:'',description:'',unit:'un',quantity:'',unitPrice:'',notes:''},
      provisional:{workId:'',number:'',title:'',clientName:'',notes:''},
      provisionalLine:{provisionalId:'',serviceId:'',description:'',unit:'un',quantity:'',unitPrice:'',notes:''},
      convertProvisional:{provisionalId:'',destination:'contract',number:'',contractId:'',addendumType:'increase'},
      addendum:{contractId:'',number:'',type:'increase',effectiveDate:today(),statedValue:'',notes:''},
      measurement:{contractId:'',competence:currentMonth(),notes:''},
      measurementLine:{measurementId:'',contractId:'',contractServiceId:'',structureId:'',measuredQuantity:'',unitPrice:'',notes:''},
      retention:{measurementId:'',retentionType:'inss',calculationType:'percentage',rate:'',fixedAmount:'',description:'',notes:''},
      measurementStatus:{measurementId:'',action:'close',reason:''},
      receivable:{measurementId:'',dueDate:today()},
      receive:{measurementId:'',accountId:'',receivedOn:today(),amount:''},
      productionPeriod:{workId:'',competence:currentMonth()},
      productionEntry:{periodId:'',employmentContractId:'',structureId:'',serviceId:'',productionDate:today(),executedQuantity:'',unitValue:'',notes:''},
      productionStatus:{periodId:'',action:'close',reason:''},
    };
    setForm({...defaults[kind],...initial}); setModal(kind);
  }
  function close(){ setModal(null); operations.clearFeedback(); }
  async function complete(action:()=>Promise<unknown>){ await action(); setRefreshToken(v=>v+1); setModal(null); }

  async function submit(){
    try{
      switch(modal){
        case 'contract': await complete(()=>operations.createContract({workId:form.workId??'',contractNumber:form.contractNumber??'',clientName:form.clientName||null,signedAt:form.signedAt||null,startDate:form.startDate||null,endDate:form.endDate||null,notes:form.notes||null})); break;
        case 'contractStatus': await complete(()=>operations.updateContractStatus(form.contractId??'',(form.status??'active') as 'draft'|'active'|'suspended'|'completed'|'cancelled')); break;
        case 'service': await complete(()=>operations.createService({name:form.name??'',unit:form.unit??'un',code:form.code||null,category:form.category||null,notes:form.notes||null})); break;
        case 'contractService': await complete(()=>operations.addContractService({contractId:form.contractId??'',serviceId:form.serviceId||null,description:form.description??'',unit:form.unit??'un',quantity:num(form.quantity??''),unitPrice:num(form.unitPrice??''),notes:form.notes||null})); break;
        case 'provisional': await complete(()=>operations.createProvisional({workId:form.workId??'',number:form.number??'',title:form.title||null,clientName:form.clientName||null,notes:form.notes||null})); break;
        case 'provisionalLine': await complete(()=>operations.addProvisionalLine({provisionalId:form.provisionalId??'',serviceId:form.serviceId||null,description:form.description??'',unit:form.unit??'un',quantity:num(form.quantity??''),unitPrice:num(form.unitPrice??''),notes:form.notes||null})); break;
        case 'convertProvisional': await complete(()=>operations.convertProvisional({provisionalId:form.provisionalId??'',destination:(form.destination??'contract') as 'contract'|'addendum',number:form.number??'',contractId:form.contractId||null,addendumType:(form.addendumType||null) as 'increase'|'reduction'|'adjustment'|null})); break;
        case 'addendum': await complete(()=>operations.createAddendum({contractId:form.contractId??'',number:form.number??'',type:(form.type??'increase') as 'increase'|'reduction'|'adjustment',effectiveDate:form.effectiveDate||null,statedValue:form.statedValue?num(form.statedValue):null,notes:form.notes||null})); break;
        case 'measurement': await complete(()=>operations.createMeasurement({contractId:form.contractId??'',competence:form.competence??currentMonth(),notes:form.notes||null})); break;
        case 'measurementLine': await complete(()=>operations.addMeasurementLine({measurementId:form.measurementId??'',contractServiceId:form.contractServiceId??'',structureId:form.structureId||null,measuredQuantity:num(form.measuredQuantity??''),unitPrice:num(form.unitPrice??''),notes:form.notes||null})); break;
        case 'retention': await complete(()=>operations.addRetention({measurementId:form.measurementId??'',retentionType:(form.retentionType??'inss') as 'inss'|'iss'|'rt'|'other',calculationType:(form.calculationType??'percentage') as 'percentage'|'fixed',rate:form.rate?num(form.rate):null,fixedAmount:form.fixedAmount?num(form.fixedAmount):null,description:form.description||null,notes:form.notes||null})); break;
        case 'measurementStatus': await complete(()=>operations.setMeasurementStatus(form.measurementId??'',(form.action??'close') as 'close'|'approve'|'cancel'|'reopen',form.reason||null)); break;
        case 'receivable': await complete(()=>operations.generateMeasurementReceivable(form.measurementId??'',form.dueDate??today())); break;
        case 'receive': await complete(()=>operations.receiveMeasurement(form.measurementId??'',form.accountId??'',form.receivedOn??today(),num(form.amount??''))); break;
        case 'productionPeriod': await complete(()=>operations.createProductionPeriod({workId:form.workId??'',competence:form.competence??currentMonth()})); break;
        case 'productionEntry': await complete(()=>operations.addProductionEntry({periodId:form.periodId??'',employmentContractId:form.employmentContractId??'',structureId:form.structureId??'',serviceId:form.serviceId??'',productionDate:form.productionDate??today(),executedQuantity:num(form.executedQuantity??''),unitValue:form.unitValue?num(form.unitValue):null,notes:form.notes||null})); break;
        case 'productionStatus': await complete(()=>operations.setProductionPeriodStatus(form.periodId??'',(form.action??'close') as 'close'|'reopen',form.reason||null)); break;
        default: break;
      }
    }catch{ /* feedback stays in dialog */ }
  }

  const titles:Record<Exclude<ModalKind,null>,string>={contract:'Novo contrato',contractStatus:'Status do contrato',service:'Novo serviço',contractService:'Serviço do contrato',provisional:'Novo provisório',provisionalLine:'Item do provisório',convertProvisional:'Converter provisório',addendum:'Novo aditivo',measurement:'Nova medição',measurementLine:'Item da medição',retention:'Nova retenção',measurementStatus:'Status da medição',receivable:'Gerar conta a receber',receive:'Receber medição',productionPeriod:'Novo período de produção',productionEntry:'Lançar produção',productionStatus:'Fechar / reabrir produção'};
  let content=null;
  if(modal==='contract') content=<div className="engineering-form-grid"><Select label="Obra" value={form.workId??''} onChange={e=>field('workId',e.target.value)} options={workOptions} required/><Input label="Número do contrato" value={form.contractNumber??''} onChange={e=>field('contractNumber',e.target.value)} required/><Input label="Cliente" value={form.clientName??''} onChange={e=>field('clientName',e.target.value)}/><Input label="Assinatura" type="date" value={form.signedAt??''} onChange={e=>field('signedAt',e.target.value)}/><Input label="Início" type="date" value={form.startDate??''} onChange={e=>field('startDate',e.target.value)}/><Input label="Fim" type="date" value={form.endDate??''} onChange={e=>field('endDate',e.target.value)}/><Input label="Observação" value={form.notes??''} onChange={e=>field('notes',e.target.value)}/></div>;
  if(modal==='contractStatus') content=<div className="engineering-form-grid"><Select label="Contrato" value={form.contractId??''} onChange={e=>field('contractId',e.target.value)} options={contractOptions} required/><Select label="Status" value={form.status??'active'} onChange={e=>field('status',e.target.value)} options={[{value:'draft',label:'Rascunho'},{value:'active',label:'Ativo'},{value:'suspended',label:'Suspenso'},{value:'completed',label:'Concluído'},{value:'cancelled',label:'Cancelado'}]}/></div>;
  if(modal==='service') content=<div className="engineering-form-grid"><Input label="Serviço" value={form.name??''} onChange={e=>field('name',e.target.value)} required/><Input label="Unidade" value={form.unit??'un'} onChange={e=>field('unit',e.target.value)} required/><Input label="Código" value={form.code??''} onChange={e=>field('code',e.target.value)}/><Input label="Categoria" value={form.category??''} onChange={e=>field('category',e.target.value)}/><Input label="Observação" value={form.notes??''} onChange={e=>field('notes',e.target.value)}/></div>;
  if(modal==='contractService') content=<div className="engineering-form-grid"><Select label="Contrato" value={form.contractId??''} onChange={e=>field('contractId',e.target.value)} options={contractOptions} required/><Select label="Serviço cadastrado" value={form.serviceId??''} onChange={e=>{ const service=operational?.services.find(item=>item.id===e.target.value); field('serviceId',e.target.value); if(service){field('description',service.name);field('unit',service.unit);} }} options={serviceOptions}/><Input label="Descrição" value={form.description??''} onChange={e=>field('description',e.target.value)} required/><Input label="Unidade" value={form.unit??'un'} onChange={e=>field('unit',e.target.value)} required/><Input label="Quantidade" type="number" min="0" step="0.01" value={form.quantity??''} onChange={e=>field('quantity',e.target.value)} required/><Input label="Valor unitário" type="number" min="0" step="0.01" value={form.unitPrice??''} onChange={e=>field('unitPrice',e.target.value)} required/><Input label="Observação" value={form.notes??''} onChange={e=>field('notes',e.target.value)}/></div>;
  if(modal==='provisional') content=<div className="engineering-form-grid"><Select label="Obra" value={form.workId??''} onChange={e=>field('workId',e.target.value)} options={workOptions} required/><Input label="Número" value={form.number??''} onChange={e=>field('number',e.target.value)} required/><Input label="Título" value={form.title??''} onChange={e=>field('title',e.target.value)}/><Input label="Cliente" value={form.clientName??''} onChange={e=>field('clientName',e.target.value)}/><Input label="Observação" value={form.notes??''} onChange={e=>field('notes',e.target.value)}/></div>;
  if(modal==='provisionalLine') content=<div className="engineering-form-grid"><Select label="Provisório" value={form.provisionalId??''} onChange={e=>field('provisionalId',e.target.value)} options={provisionalOptions} required/><Select label="Serviço cadastrado" value={form.serviceId??''} onChange={e=>{ const service=operational?.services.find(item=>item.id===e.target.value); field('serviceId',e.target.value); if(service){field('description',service.name);field('unit',service.unit);} }} options={serviceOptions}/><Input label="Descrição" value={form.description??''} onChange={e=>field('description',e.target.value)} required/><Input label="Unidade" value={form.unit??'un'} onChange={e=>field('unit',e.target.value)} required/><Input label="Quantidade" type="number" min="0" step="0.01" value={form.quantity??''} onChange={e=>field('quantity',e.target.value)} required/><Input label="Valor unitário" type="number" min="0" step="0.01" value={form.unitPrice??''} onChange={e=>field('unitPrice',e.target.value)} required/></div>;
  if(modal==='convertProvisional') content=<div className="engineering-form-grid"><Select label="Provisório" value={form.provisionalId??''} onChange={e=>field('provisionalId',e.target.value)} options={provisionalOptions} required/><Select label="Converter em" value={form.destination??'contract'} onChange={e=>field('destination',e.target.value)} options={[{value:'contract',label:'Contrato'},{value:'addendum',label:'Aditivo'}]}/><Input label="Número de destino" value={form.number??''} onChange={e=>field('number',e.target.value)} required/>{form.destination==='addendum'&&<><Select label="Contrato existente" value={form.contractId??''} onChange={e=>field('contractId',e.target.value)} options={contractOptions} required/><Select label="Tipo" value={form.addendumType??'increase'} onChange={e=>field('addendumType',e.target.value)} options={[{value:'increase',label:'Acréscimo'},{value:'reduction',label:'Redução'},{value:'adjustment',label:'Ajuste'}]}/></>}</div>;
  if(modal==='addendum') content=<div className="engineering-form-grid"><Select label="Contrato" value={form.contractId??''} onChange={e=>field('contractId',e.target.value)} options={contractOptions} required/><Input label="Número" value={form.number??''} onChange={e=>field('number',e.target.value)} required/><Select label="Tipo" value={form.type??'increase'} onChange={e=>field('type',e.target.value)} options={[{value:'increase',label:'Acréscimo'},{value:'reduction',label:'Redução'},{value:'adjustment',label:'Ajuste'}]}/><Input label="Vigência" type="date" value={form.effectiveDate??today()} onChange={e=>field('effectiveDate',e.target.value)}/><Input label="Valor declarado" type="number" min="0" step="0.01" value={form.statedValue??''} onChange={e=>field('statedValue',e.target.value)}/><Input label="Observação" value={form.notes??''} onChange={e=>field('notes',e.target.value)}/></div>;
  if(modal==='measurement') content=<div className="engineering-form-grid"><Select label="Contrato" value={form.contractId??''} onChange={e=>field('contractId',e.target.value)} options={contractOptions} required/><Input label="Competência" type="month" value={form.competence??currentMonth()} onChange={e=>field('competence',e.target.value)} required/><Input label="Observação" value={form.notes??''} onChange={e=>field('notes',e.target.value)}/></div>;
  if(modal==='measurementLine') content=<div className="engineering-form-grid"><Select label="Medição" value={form.measurementId??''} onChange={e=>{ const m=operational?.measurements.find(item=>item.id===e.target.value); field('measurementId',e.target.value); field('contractId',m?.contractId??''); }} options={measurementOptions} required/><Select label="Serviço do contrato" value={form.contractServiceId??''} onChange={e=>{ const item=operational?.contractServices.find(service=>service.id===e.target.value); field('contractServiceId',e.target.value); if(item) field('unitPrice',String(item.unitPrice)); }} options={contractServiceOptions} required/><Select label="Torre / pavimento / unidade" value={form.structureId??''} onChange={e=>field('structureId',e.target.value)} options={option(operational?.structures??[])}/><Input label="Quantidade medida" type="number" min="0.01" step="0.01" value={form.measuredQuantity??''} onChange={e=>field('measuredQuantity',e.target.value)} required/><Input label="Valor unitário" type="number" min="0" step="0.01" value={form.unitPrice??''} onChange={e=>field('unitPrice',e.target.value)} required/></div>;
  if(modal==='retention') content=<div className="engineering-form-grid"><Select label="Medição" value={form.measurementId??''} onChange={e=>field('measurementId',e.target.value)} options={measurementOptions} required/><Select label="Retenção" value={form.retentionType??'inss'} onChange={e=>field('retentionType',e.target.value)} options={[{value:'inss',label:'INSS'},{value:'iss',label:'ISS'},{value:'rt',label:'RT'},{value:'other',label:'Outra'}]}/><Select label="Cálculo" value={form.calculationType??'percentage'} onChange={e=>field('calculationType',e.target.value)} options={[{value:'percentage',label:'Percentual'},{value:'fixed',label:'Valor fixo'}]}/>{form.calculationType==='fixed'?<Input label="Valor" type="number" min="0" step="0.01" value={form.fixedAmount??''} onChange={e=>field('fixedAmount',e.target.value)} required/>:<Input label="Percentual" type="number" min="0" step="0.01" value={form.rate??''} onChange={e=>field('rate',e.target.value)} required/>}<Input label="Descrição" value={form.description??''} onChange={e=>field('description',e.target.value)}/></div>;
  if(modal==='measurementStatus') content=<div className="engineering-form-grid"><Select label="Medição" value={form.measurementId??''} onChange={e=>field('measurementId',e.target.value)} options={measurementOptions} required/><Select label="Ação" value={form.action??'close'} onChange={e=>field('action',e.target.value)} options={[{value:'close',label:'Fechar'},{value:'approve',label:'Aprovar'},{value:'reopen',label:'Reabrir'},{value:'cancel',label:'Cancelar'}]}/><Input label="Motivo / observação" value={form.reason??''} onChange={e=>field('reason',e.target.value)}/></div>;
  if(modal==='receivable') content=<div className="engineering-form-grid"><Select label="Medição" value={form.measurementId??''} onChange={e=>field('measurementId',e.target.value)} options={measurementOptions} required/><Input label="Vencimento" type="date" value={form.dueDate??today()} onChange={e=>field('dueDate',e.target.value)} required/></div>;
  if(modal==='receive') content=<div className="engineering-form-grid"><Select label="Medição" value={form.measurementId??''} onChange={e=>field('measurementId',e.target.value)} options={measurementOptions} required/><Select label="Conta" value={form.accountId??''} onChange={e=>field('accountId',e.target.value)} options={accountOptions} required/><Input label="Data do recebimento" type="date" value={form.receivedOn??today()} onChange={e=>field('receivedOn',e.target.value)} required/><Input label="Valor recebido" type="number" min="0.01" step="0.01" value={form.amount??''} onChange={e=>field('amount',e.target.value)} required/></div>;
  if(modal==='productionPeriod') content=<div className="engineering-form-grid"><Select label="Obra" value={form.workId??''} onChange={e=>field('workId',e.target.value)} options={workOptions} required/><Input label="Competência" type="month" value={form.competence??currentMonth()} onChange={e=>field('competence',e.target.value)} required/></div>;
  if(modal==='productionEntry') content=<div className="engineering-form-grid"><Select label="Período" value={form.periodId??''} onChange={e=>{field('periodId',e.target.value);field('structureId','');}} options={periodOptions} required/><Select label="Colaborador" value={form.employmentContractId??''} onChange={e=>field('employmentContractId',e.target.value)} options={employeeOptions} required/><Select label="Torre / pavimento / unidade" value={form.structureId??''} onChange={e=>field('structureId',e.target.value)} options={structureOptions} required/><Select label="Serviço" value={form.serviceId??''} onChange={e=>field('serviceId',e.target.value)} options={serviceOptions} required/><Input label="Data" type="date" value={form.productionDate??today()} onChange={e=>field('productionDate',e.target.value)} required/><Input label="Quantidade executada" type="number" min="0.01" step="0.01" value={form.executedQuantity??''} onChange={e=>field('executedQuantity',e.target.value)} required/><Input label="Valor unitário" type="number" min="0" step="0.01" value={form.unitValue??''} onChange={e=>field('unitValue',e.target.value)}/><Input label="Observação" value={form.notes??''} onChange={e=>field('notes',e.target.value)}/></div>;
  if(modal==='productionStatus') content=<div className="engineering-form-grid"><Select label="Período" value={form.periodId??''} onChange={e=>field('periodId',e.target.value)} options={periodOptions} required/><Select label="Ação" value={form.action??'close'} onChange={e=>field('action',e.target.value)} options={[{value:'close',label:'Fechar'},{value:'reopen',label:'Reabrir'}]}/><Input label="Motivo" value={form.reason??''} onChange={e=>field('reason',e.target.value)}/></div>;

  return <section className="engineering-overview" aria-labelledby="engineering-title">
    <div className="engineering-overview__heading"><div><span className="ui-muted">Módulo operacional</span><h1 id="engineering-title">Engenharia</h1></div><p className="ui-muted">Contratos, medições, produção, provisórios e aditivos integrados à empresa selecionada.</p></div>
    <Tabs items={tabs} activeId={activeTab} onChange={setActiveTab} ariaLabel="Seções da engenharia"/>
    {operations.state.errorMessage&&modal===null&&<Feedback tone="danger" title="Operação não concluída" message={operations.state.errorMessage}/>} {operations.state.successMessage&&modal===null&&<Feedback tone="success" title="Concluído" message={operations.state.successMessage}/>} 
    <div className="engineering-workspace" role="tabpanel" tabIndex={0}><div className="engineering-workspace__canvas">
      {activeTab==='contratos'&&<Card title="Contratos" description="Valor atualizado, medido e saldo" actions={<div className="engineering-actions"><Button size="sm" onClick={()=>open('contract')}>Novo contrato</Button><Button size="sm" variant="secondary" onClick={()=>open('service')}>Novo serviço</Button><Button size="sm" variant="secondary" onClick={()=>open('contractService')}>Adicionar serviço</Button><Button size="sm" variant="tertiary" onClick={()=>open('contractStatus')}>Alterar status</Button></div>}>{data.contracts.length===0?empty:<div className="engineering-data-list">{data.contracts.map(item=><div className="engineering-data-row" key={item.contractId}><div><strong>{item.contractNumber}</strong><span>{item.status}</span></div><div><span>{currency.format(item.updatedContractValue)}</span><span>Medido {currency.format(item.measuredNet)} · {item.measuredPercent.toFixed(2)}%</span><span>Saldo {currency.format(item.grossBalance)}</span></div></div>)}</div>}</Card>}
      {activeTab==='medicoes'&&<Card title="Medições" description="Itens, retenções, aprovação e Financeiro" actions={<div className="engineering-actions"><Button size="sm" onClick={()=>open('measurement')}>Nova medição</Button><Button size="sm" variant="secondary" onClick={()=>open('measurementLine')}>Adicionar item</Button><Button size="sm" variant="secondary" onClick={()=>open('retention')}>Retenção</Button><Button size="sm" variant="secondary" onClick={()=>open('measurementStatus')}>Fechar / aprovar</Button><Button size="sm" variant="tertiary" onClick={()=>open('receivable')}>Gerar a receber</Button><Button size="sm" variant="tertiary" onClick={()=>open('receive')}>Receber</Button></div>}>{data.measurements.length===0?empty:<div className="engineering-data-list">{data.measurements.map(item=><div className="engineering-data-row" key={item.measurementId}><div><strong>{item.competence}</strong><span>{item.status}</span></div><div><span>Bruto {currency.format(item.grossAmount)}</span><span>Retido {currency.format(item.retainedAmount)}</span><span>Líquido {currency.format(item.netAmount)}</span></div></div>)}</div>}</Card>}
      {activeTab==='producao'&&<Card title="Produção" description="Lançamento por colaborador, estrutura e competência" actions={<div className="engineering-actions"><Button size="sm" onClick={()=>open('productionPeriod')}>Novo período</Button><Button size="sm" variant="secondary" onClick={()=>open('productionEntry')}>Lançar produção</Button><Button size="sm" variant="secondary" onClick={()=>open('productionStatus')}>Fechar / reabrir</Button></div>}>{data.production.length===0?empty:<div className="engineering-data-list">{data.production.map((item,index)=><div className="engineering-data-row" key={`${item.employmentContractId}-${item.competence}-${index}`}><div><strong>{item.competence}</strong><span>Vínculo {item.employmentContractId.slice(0,8)}</span></div><div><span>Qtd. {item.executedQuantity}</span><span>{currency.format(item.productionValue)}</span></div></div>)}</div>}</Card>}
      {activeTab==='aditivos'&&<Card title="Aditivos" description="Acréscimos, reduções e ajustes" actions={<div className="engineering-actions"><Button size="sm" onClick={()=>open('addendum')}>Novo aditivo</Button></div>}>{data.addenda.length===0?empty:<div className="engineering-data-list">{data.addenda.map(item=><div className="engineering-data-row" key={item.id}><div><strong>{item.addendumNumber}</strong><span>{item.addendumType} · {item.status}</span></div><div><span>{item.statedValue===null?'Valor por linhas':currency.format(item.statedValue)}</span></div></div>)}</div>}</Card>}
      {activeTab==='provisorios'&&<Card title="Provisórios" description="Negociação editável antes da conversão" actions={<div className="engineering-actions"><Button size="sm" onClick={()=>open('provisional')}>Novo provisório</Button><Button size="sm" variant="secondary" onClick={()=>open('provisionalLine')}>Adicionar item</Button><Button size="sm" variant="tertiary" onClick={()=>open('convertProvisional')}>Converter</Button></div>}>{data.provisionals.length===0?empty:<div className="engineering-data-list">{data.provisionals.map(item=><div className="engineering-data-row" key={item.id}><div><strong>{item.provisionalNumber}</strong><span>{item.title??'Sem título'}</span></div><div><span>{item.status}</span><span>{item.clientName??'Cliente não informado'}</span></div></div>)}</div>}</Card>}
    </div></div>
    <Dialog open={modal!==null} title={modal?titles[modal]:'Engenharia'} description="Operação vinculada exclusivamente à empresa selecionada." loading={operations.state.busy} onClose={close} onBack={close} onConfirm={modal?()=>{void submit();}:undefined}>{operations.state.errorMessage&&<Feedback tone="danger" title="Não foi possível salvar" message={operations.state.errorMessage}/>} {content}</Dialog>
  </section>;
}
