import { useMemo, useState } from 'react';
import { Button } from '../../../shared/ui/Button';
import { Card } from '../../../shared/ui/Card';
import { Dialog } from '../../../shared/ui/Dialog';
import { EmptyState } from '../../../shared/ui/Feedback';
import { Input } from '../../../shared/ui/Input';
import { Select } from '../../../shared/ui/Select';
import type { EngineeringProductionSnapshot } from '../infrastructure/EngineeringProductionReadRepository';

interface Props { open:boolean;workName:string;contractNumber:string;snapshot:EngineeringProductionSnapshot;onClose:()=>void; }
const currency=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const qty=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:3});
const monthLabel=(value:string)=>{const [y,m]=value.slice(0,7).split('-');return m&&y?`${m}/${y}`:value;};
const dateLabel=(value:string)=>{const [y,m,d]=value.slice(0,10).split('-');return d&&m&&y?`${d}/${m}/${y}`:value;};

export function EngineeringProductionReportDialog({open,workName,contractNumber,snapshot,onClose}:Props){
 const [periodId,setPeriodId]=useState('all');const [employeeId,setEmployeeId]=useState('all');const [search,setSearch]=useState('');
 const employees=useMemo(()=>{const map=new Map<string,string>();for(const entry of snapshot.entries){const shares=entry.participants.length?entry.participants:[{employmentContractId:entry.employmentContractId,employeeName:entry.employeeName,percentage:100,value:entry.productionValue??0}];for(const share of shares)map.set(share.employmentContractId,share.employeeName);}return [...map].sort((a,b)=>a[1].localeCompare(b[1],'pt-BR'));},[snapshot.entries]);
 const rows=useMemo(()=>{const term=search.trim().toLocaleLowerCase('pt-BR');return snapshot.entries.flatMap(entry=>{const shares=entry.participants.length?entry.participants:[{employmentContractId:entry.employmentContractId,employeeName:entry.employeeName,percentage:100,value:entry.productionValue??0}];return shares.filter(share=>(employeeId==='all'||share.employmentContractId===employeeId)&&(periodId==='all'||entry.periodId===periodId)).map(share=>({entry,share}));}).filter(({entry,share})=>!term||`${share.employeeName} ${entry.structureName} ${entry.serviceName} ${entry.notes??''}`.toLocaleLowerCase('pt-BR').includes(term));},[snapshot.entries,employeeId,periodId,search]);
 const total=rows.reduce((sum,row)=>sum+row.share.value,0);const structures=new Set(rows.map(row=>row.entry.structureName)).size;const participants=new Set(rows.map(row=>row.share.employmentContractId)).size;
 return <Dialog open={open} title="Relatório de produção" description={`${workName} · Contrato ${contractNumber}`} onClose={onClose} onBack={onClose} footer={<Button onClick={()=>window.print()}>Imprimir relatório</Button>}><section className="engineering-production-report"><div className="engineering-production-report__filters"><Select label="Competência" value={periodId} onChange={e=>setPeriodId(e.target.value)} options={[{value:'all',label:'Todas'},...snapshot.periods.map(p=>({value:p.id,label:`${monthLabel(p.competence)} · ${p.status==='closed'?'Fechada':'Aberta'}`}))]}/><Select label="Colaborador" value={employeeId} onChange={e=>setEmployeeId(e.target.value)} options={[{value:'all',label:'Todos'},...employees.map(([id,name])=>({value:id,label:name}))]}/><Input label="Buscar" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Torre, unidade ou serviço"/></div><div className="engineering-production-report__kpis"><Card title="Valor produzido"><strong>{currency.format(total)}</strong><span>No filtro atual</span></Card><Card title="Participações"><strong>{rows.length}</strong><span>{participants} colaborador(es)</span></Card><Card title="Estruturas"><strong>{structures}</strong><span>Torre/unidade no relatório</span></Card></div>{rows.length===0?<EmptyState title="Sem dados no filtro" message="Ajuste os filtros para localizar a produção desejada."/>:<div className="engineering-production-report__table-wrap"><table className="engineering-production-report__table"><thead><tr><th>Data</th><th>Colaborador</th><th>Estrutura</th><th>Serviço</th><th>Qtd.</th><th>Participação</th><th>Valor</th></tr></thead><tbody>{rows.map(({entry,share})=><tr key={`${entry.id}-${share.employmentContractId}`}><td>{dateLabel(entry.productionDate)}</td><td><strong>{share.employeeName}</strong></td><td>{entry.structureName}</td><td>{entry.serviceName}</td><td>{qty.format(entry.executedQuantity)}</td><td>{qty.format(share.percentage)}%</td><td><strong>{currency.format(share.value)}</strong></td></tr>)}</tbody></table></div>}</section></Dialog>;
}
