import { useState } from 'react';
import { Button } from '../../../shared/ui/Button';
import { Dialog } from '../../../shared/ui/Dialog';
import { Feedback } from '../../../shared/ui/Feedback';
import { Input } from '../../../shared/ui/Input';
import { Select } from '../../../shared/ui/Select';
import type { EngineeringOperationalSnapshot } from '../application/EngineeringOperationsRepository';
import { useEngineeringOperations } from './useEngineeringOperations';

type TabId='contratos'|'medicoes'|'producao'|'aditivos'|'provisorios';
type Kind='work'|'structure'|'contract'|'contractStatus'|'service'|'contractService'|'allocation'|'provisional'|'provisionalLine'|'convert'|'addendum'|'addendumLine'|'measurement'|'measurementLine'|'retention'|'measurementStatus'|'receivable'|'receive'|'productionPeriod'|'productionEntry'|'productionStatus'|null;
interface Props { activeTab:TabId; scope:{tenantId:string;companyId:string}; onChanged:()=>void; }
const currency=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const today=()=>new Date().toISOString().slice(0,10);
const currentMonth=()=>new Date().toISOString().slice(0,7);
const num=(value:string)=>{const result=Number(value.replace(',','.'));return Number.isFinite(result)?result:0;};
const opts=(items:readonly {id:string;name:string}[],placeholder='Selecione…')=>[{value:'',label:placeholder},...items.map(item=>({value:item.id,label:item.name}))];

export function EngineeringOperationsPanel({activeTab,scope,onChanged}:Props){
  const operations=useEngineeringOperations(scope);
  const data=operations.state.data;
  const [kind,setKind]=useState<Kind>(null);
  const [form,setForm]=useState<Record<string,string>>({});
  const field=(name:string,value:string)=>setForm(current=>({...current,[name]:value}));
  const workOptions=opts(data?.works??[]);
  const contractOptions=opts((data?.contracts??[]).map(item=>({id:item.id,name:`${item.contractNumber} · ${item.status}`})));
  const serviceOptions=opts((data?.services??[]).map(item=>({id:item.id,name:`${item.name} · ${item.unit}`})));
  const provisionalOptions=opts((data?.provisionals??[]).filter(item=>item.status!=='converted'&&item.status!=='cancelled').map(item=>({id:item.id,name:`${item.number} · ${item.status}`})));
  const measurementOptions=opts((data?.measurements??[]).map(item=>({id:item.id,name:`${item.competence.slice(0,7)} · ${item.status}`})));
  const periodOptions=opts((data?.productionPeriods??[]).map(item=>({id:item.id,name:`${item.competence.slice(0,7)} · ${item.status}`})));
  const addendumOptions=opts((data?.addenda??[]).map(item=>({id:item.id,name:`${item.number} · ${item.status}`})));
  const employeeOptions=opts(data?.employees??[]);
  const accountOptions=opts(data?.accounts??[]);
  const selectedContract=form.contractId??'';
  const selectedContractRow=data?.contracts.find(item=>item.id===selectedContract);
  const contractServiceOptions=opts((data?.contractServices??[]).filter(item=>!selectedContract||item.contractId===selectedContract).map(item=>({id:item.id,name:`${item.description} · ${currency.format(item.unitPrice)}/${item.unit}`})));
  const selectedPeriod=data?.productionPeriods.find(item=>item.id===form.periodId);
  const selectedWork=form.workId||selectedContractRow?.workId||selectedPeriod?.workId||'';
  const structureOptions=opts((data?.structures??[]).filter(item=>!selectedWork||item.workId===selectedWork));

  function open(next:Exclude<Kind,null>){
    operations.clearFeedback();
    const defaults:Record<Exclude<Kind,null>,Record<string,string>>={
      work:{name:'',code:'',clientName:'',city:'',state:'',notes:''},
      structure:{workId:'',parentId:'',type:'tower',code:'',name:''},
      contract:{workId:'',contractNumber:'',clientName:'',signedAt:'',startDate:'',endDate:'',notes:''},
      contractStatus:{contractId:'',status:'active'},service:{name:'',unit:'un',code:'',category:'',notes:''},
      contractService:{contractId:'',serviceId:'',description:'',unit:'un',quantity:'',unitPrice:'',notes:''},
      allocation:{contractId:'',workId:'',contractServiceId:'',structureId:'',quantity:'',notes:''},
      provisional:{workId:'',number:'',title:'',clientName:'',notes:''},
      provisionalLine:{provisionalId:'',serviceId:'',description:'',unit:'un',quantity:'',unitPrice:'',notes:''},
      convert:{provisionalId:'',destination:'contract',number:'',contractId:'',addendumType:'increase'},
      addendum:{contractId:'',number:'',type:'increase',effectiveDate:today(),statedValue:'',notes:''},
      addendumLine:{addendumId:'',contractId:'',contractServiceId:'',serviceId:'',description:'',unit:'un',quantityDelta:'',unitPrice:'',notes:''},
      measurement:{contractId:'',competence:currentMonth(),notes:''},
      measurementLine:{measurementId:'',contractId:'',contractServiceId:'',structureId:'',measuredQuantity:'',unitPrice:'',notes:''},
      retention:{measurementId:'',retentionType:'inss',calculationType:'percentage',rate:'',fixedAmount:'',description:'',notes:''},
      measurementStatus:{measurementId:'',action:'close',reason:''},receivable:{measurementId:'',dueDate:today()},receive:{measurementId:'',accountId:'',receivedOn:today(),amount:''},
      productionPeriod:{workId:'',competence:currentMonth()},productionEntry:{periodId:'',employmentContractId:'',structureId:'',serviceId:'',productionDate:today(),executedQuantity:'',unitValue:'',notes:''},productionStatus:{periodId:'',action:'close',reason:''},
    };
    setForm(defaults[next]);setKind(next);
  }
  const close=()=>{setKind(null);operations.clearFeedback();};
  async function done(action:()=>Promise<unknown>){await action();onChanged();setKind(null);}
  async function submit(){try{switch(kind){
    case 'work':await done(()=>operations.createWork({name:form.name??'',code:form.code||null,clientName:form.clientName||null,city:form.city||null,state:form.state||null,notes:form.notes||null}));break;
    case 'structure':await done(()=>operations.createStructure({workId:form.workId??'',parentId:form.parentId||null,type:(form.type??'tower') as Parameters<typeof operations.createStructure>[0]['type'],code:form.code||null,name:form.name??''}));break;
    case 'contract':await done(()=>operations.createContract({workId:form.workId??'',contractNumber:form.contractNumber??'',clientName:form.clientName||null,signedAt:form.signedAt||null,startDate:form.startDate||null,endDate:form.endDate||null,notes:form.notes||null}));break;
    case 'contractStatus':await done(()=>operations.updateContractStatus(form.contractId??'',(form.status??'active') as Parameters<typeof operations.updateContractStatus>[1]));break;
    case 'service':await done(()=>operations.createService({name:form.name??'',unit:form.unit??'un',code:form.code||null,category:form.category||null,notes:form.notes||null}));break;
    case 'contractService':await done(()=>operations.addContractService({contractId:form.contractId??'',serviceId:form.serviceId||null,description:form.description??'',unit:form.unit??'un',quantity:num(form.quantity??''),unitPrice:num(form.unitPrice??''),notes:form.notes||null}));break;
    case 'allocation':await done(()=>operations.allocateContractService({workId:form.workId||selectedContractRow?.workId||'',contractServiceId:form.contractServiceId??'',structureId:form.structureId??'',quantity:num(form.quantity??''),notes:form.notes||null}));break;
    case 'provisional':await done(()=>operations.createProvisional({workId:form.workId??'',number:form.number??'',title:form.title||null,clientName:form.clientName||null,notes:form.notes||null}));break;
    case 'provisionalLine':await done(()=>operations.addProvisionalLine({provisionalId:form.provisionalId??'',serviceId:form.serviceId||null,description:form.description??'',unit:form.unit??'un',quantity:num(form.quantity??''),unitPrice:num(form.unitPrice??''),notes:form.notes||null}));break;
    case 'convert':await done(()=>operations.convertProvisional({provisionalId:form.provisionalId??'',destination:(form.destination??'contract') as 'contract'|'addendum',number:form.number??'',contractId:form.contractId||null,addendumType:(form.addendumType||null) as 'increase'|'reduction'|'adjustment'|null}));break;
    case 'addendum':await done(()=>operations.createAddendum({contractId:form.contractId??'',number:form.number??'',type:(form.type??'increase') as 'increase'|'reduction'|'adjustment',effectiveDate:form.effectiveDate||null,statedValue:form.statedValue?num(form.statedValue):null,notes:form.notes||null}));break;
    case 'addendumLine':await done(()=>operations.addAddendumLine({addendumId:form.addendumId??'',contractServiceId:form.contractServiceId||null,serviceId:form.serviceId||null,description:form.description??'',unit:form.unit??'un',quantityDelta:num(form.quantityDelta??''),unitPrice:num(form.unitPrice??''),notes:form.notes||null}));break;
    case 'measurement':await done(()=>operations.createMeasurement({contractId:form.contractId??'',competence:form.competence??currentMonth(),notes:form.notes||null}));break;
    case 'measurementLine':await done(()=>operations.addMeasurementLine({measurementId:form.measurementId??'',contractServiceId:form.contractServiceId??'',structureId:form.structureId||null,measuredQuantity:num(form.measuredQuantity??''),unitPrice:num(form.unitPrice??''),notes:form.notes||null}));break;
    case 'retention':await done(()=>operations.addRetention({measurementId:form.measurementId??'',retentionType:(form.retentionType??'inss') as 'inss'|'iss'|'rt'|'other',calculationType:(form.calculationType??'percentage') as 'percentage'|'fixed',rate:form.rate?num(form.rate):null,fixedAmount:form.fixedAmount?num(form.fixedAmount):null,description:form.description||null,notes:form.notes||null}));break;
    case 'measurementStatus':await done(()=>operations.setMeasurementStatus(form.measurementId??'',(form.action??'close') as 'close'|'approve'|'cancel'|'reopen',form.reason||null));break;
    case 'receivable':await done(()=>operations.generateMeasurementReceivable(form.measurementId??'',form.dueDate??today()));break;
    case 'receive':await done(()=>operations.receiveMeasurement(form.measurementId??'',form.accountId??'',form.receivedOn??today(),num(form.amount??'')));break;
    case 'productionPeriod':await done(()=>operations.createProductionPeriod({workId:form.workId??'',competence:form.competence??currentMonth()}));break;
    case 'productionEntry':await done(()=>operations.addProductionEntry({periodId:form.periodId??'',employmentContractId:form.employmentContractId??'',structureId:form.structureId??'',serviceId:form.serviceId??'',productionDate:form.productionDate??today(),executedQuantity:num(form.executedQuantity??''),unitValue:form.unitValue?num(form.unitValue):null,notes:form.notes||null}));break;
    case 'productionStatus':await done(()=>operations.setProductionPeriodStatus(form.periodId??'',(form.action??'close') as 'close'|'reopen',form.reason||null));break;
    default:break;
  }}catch{}}

  const actions:Record<TabId,React.ReactNode>={
    contratos:<><Button size="sm" onClick={()=>open('work')}>Nova obra</Button><Button size="sm" variant="secondary" onClick={()=>open('structure')}>Estrutura</Button><Button size="sm" onClick={()=>open('contract')}>Novo contrato</Button><Button size="sm" variant="secondary" onClick={()=>open('service')}>Novo serviço</Button><Button size="sm" variant="secondary" onClick={()=>open('contractService')}>Serviço no contrato</Button><Button size="sm" variant="secondary" onClick={()=>open('allocation')}>Distribuir serviço</Button><Button size="sm" variant="tertiary" onClick={()=>open('contractStatus')}>Status</Button></>,
    medicoes:<><Button size="sm" onClick={()=>open('measurement')}>Nova medição</Button><Button size="sm" variant="secondary" onClick={()=>open('measurementLine')}>Adicionar item</Button><Button size="sm" variant="secondary" onClick={()=>open('retention')}>Retenção</Button><Button size="sm" variant="secondary" onClick={()=>open('measurementStatus')}>Fechar / aprovar</Button><Button size="sm" variant="tertiary" onClick={()=>open('receivable')}>Gerar a receber</Button><Button size="sm" variant="tertiary" onClick={()=>open('receive')}>Receber</Button></>,
    producao:<><Button size="sm" onClick={()=>open('productionPeriod')}>Novo período</Button><Button size="sm" variant="secondary" onClick={()=>open('productionEntry')}>Lançar produção</Button><Button size="sm" variant="secondary" onClick={()=>open('productionStatus')}>Fechar / reabrir</Button></>,
    aditivos:<><Button size="sm" onClick={()=>open('addendum')}>Novo aditivo</Button><Button size="sm" variant="secondary" onClick={()=>open('addendumLine')}>Adicionar item</Button></>,
    provisorios:<><Button size="sm" onClick={()=>open('provisional')}>Novo provisório</Button><Button size="sm" variant="secondary" onClick={()=>open('provisionalLine')}>Adicionar item</Button><Button size="sm" variant="tertiary" onClick={()=>open('convert')}>Converter</Button></>,
  };

  const title:Record<Exclude<Kind,null>,string>={work:'Nova obra',structure:'Nova estrutura',contract:'Novo contrato',contractStatus:'Status do contrato',service:'Novo serviço',contractService:'Serviço do contrato',allocation:'Distribuir serviço',provisional:'Novo provisório',provisionalLine:'Item do provisório',convert:'Converter provisório',addendum:'Novo aditivo',addendumLine:'Item do aditivo',measurement:'Nova medição',measurementLine:'Item da medição',retention:'Nova retenção',measurementStatus:'Status da medição',receivable:'Gerar conta a receber',receive:'Receber medição',productionPeriod:'Novo período',productionEntry:'Lançar produção',productionStatus:'Fechar / reabrir produção'};
  let content=null;
  if(kind==='work')content=<div className="engineering-form-grid"><Input label="Nome da obra" value={form.name??''} onChange={e=>field('name',e.target.value)} required/><Input label="Código" value={form.code??''} onChange={e=>field('code',e.target.value)}/><Input label="Cliente" value={form.clientName??''} onChange={e=>field('clientName',e.target.value)}/><Input label="Cidade" value={form.city??''} onChange={e=>field('city',e.target.value)}/><Input label="UF" value={form.state??''} onChange={e=>field('state',e.target.value)}/><Input label="Observação" value={form.notes??''} onChange={e=>field('notes',e.target.value)}/></div>;
  if(kind==='structure')content=<div className="engineering-form-grid"><Select label="Obra" value={form.workId??''} onChange={e=>field('workId',e.target.value)} options={workOptions} required/><Select label="Tipo" value={form.type??'tower'} onChange={e=>field('type',e.target.value)} options={[{value:'tower',label:'Torre'},{value:'block',label:'Bloco'},{value:'floor',label:'Pavimento'},{value:'unit',label:'Unidade'},{value:'house',label:'Casa'},{value:'ground_floor',label:'Térreo'},{value:'basement',label:'Subsolo'},{value:'area',label:'Área'},{value:'other',label:'Outro'}]}/><Select label="Estrutura pai" value={form.parentId??''} onChange={e=>field('parentId',e.target.value)} options={opts((data?.structures??[]).filter(item=>item.workId===form.workId))}/><Input label="Código" value={form.code??''} onChange={e=>field('code',e.target.value)}/><Input label="Nome" value={form.name??''} onChange={e=>field('name',e.target.value)} required/></div>;
  if(kind==='contract')content=<div className="engineering-form-grid"><Select label="Obra" value={form.workId??''} onChange={e=>field('workId',e.target.value)} options={workOptions} required/><Input label="Número" value={form.contractNumber??''} onChange={e=>field('contractNumber',e.target.value)} required/><Input label="Cliente" value={form.clientName??''} onChange={e=>field('clientName',e.target.value)}/><Input label="Assinatura" type="date" value={form.signedAt??''} onChange={e=>field('signedAt',e.target.value)}/><Input label="Início" type="date" value={form.startDate??''} onChange={e=>field('startDate',e.target.value)}/><Input label="Fim" type="date" value={form.endDate??''} onChange={e=>field('endDate',e.target.value)}/></div>;
  if(kind==='contractStatus')content=<div className="engineering-form-grid"><Select label="Contrato" value={form.contractId??''} onChange={e=>field('contractId',e.target.value)} options={contractOptions} required/><Select label="Status" value={form.status??'active'} onChange={e=>field('status',e.target.value)} options={[{value:'draft',label:'Rascunho'},{value:'active',label:'Ativo'},{value:'suspended',label:'Suspenso'},{value:'completed',label:'Concluído'},{value:'cancelled',label:'Cancelado'}]}/></div>;
  if(kind==='service')content=<div className="engineering-form-grid"><Input label="Serviço" value={form.name??''} onChange={e=>field('name',e.target.value)} required/><Input label="Unidade" value={form.unit??'un'} onChange={e=>field('unit',e.target.value)} required/><Input label="Código" value={form.code??''} onChange={e=>field('code',e.target.value)}/><Input label="Categoria" value={form.category??''} onChange={e=>field('category',e.target.value)}/></div>;
  if(kind==='contractService')content=<div className="engineering-form-grid"><Select label="Contrato" value={form.contractId??''} onChange={e=>field('contractId',e.target.value)} options={contractOptions} required/><Select label="Serviço" value={form.serviceId??''} onChange={e=>{const s=data?.services.find(i=>i.id===e.target.value);field('serviceId',e.target.value);if(s){field('description',s.name);field('unit',s.unit);}}} options={serviceOptions}/><Input label="Descrição" value={form.description??''} onChange={e=>field('description',e.target.value)} required/><Input label="Unidade" value={form.unit??'un'} onChange={e=>field('unit',e.target.value)} required/><Input label="Quantidade" type="number" min="0" step="0.01" value={form.quantity??''} onChange={e=>field('quantity',e.target.value)} required/><Input label="Valor unitário" type="number" min="0" step="0.01" value={form.unitPrice??''} onChange={e=>field('unitPrice',e.target.value)} required/></div>;
  if(kind==='allocation')content=<div className="engineering-form-grid"><Select label="Contrato" value={form.contractId??''} onChange={e=>{const c=data?.contracts.find(i=>i.id===e.target.value);field('contractId',e.target.value);field('workId',c?.workId??'');field('contractServiceId','');field('structureId','');}} options={contractOptions} required/><Select label="Serviço do contrato" value={form.contractServiceId??''} onChange={e=>field('contractServiceId',e.target.value)} options={contractServiceOptions} required/><Select label="Torre / pavimento / unidade" value={form.structureId??''} onChange={e=>field('structureId',e.target.value)} options={structureOptions} required/><Input label="Quantidade distribuída" type="number" min="0.01" step="0.01" value={form.quantity??''} onChange={e=>field('quantity',e.target.value)} required/></div>;
  if(kind==='provisional')content=<div className="engineering-form-grid"><Select label="Obra" value={form.workId??''} onChange={e=>field('workId',e.target.value)} options={workOptions} required/><Input label="Número" value={form.number??''} onChange={e=>field('number',e.target.value)} required/><Input label="Título" value={form.title??''} onChange={e=>field('title',e.target.value)}/><Input label="Cliente" value={form.clientName??''} onChange={e=>field('clientName',e.target.value)}/></div>;
  if(kind==='provisionalLine')content=<div className="engineering-form-grid"><Select label="Provisório" value={form.provisionalId??''} onChange={e=>field('provisionalId',e.target.value)} options={provisionalOptions} required/><Select label="Serviço" value={form.serviceId??''} onChange={e=>{const s=data?.services.find(i=>i.id===e.target.value);field('serviceId',e.target.value);if(s){field('description',s.name);field('unit',s.unit);}}} options={serviceOptions}/><Input label="Descrição" value={form.description??''} onChange={e=>field('description',e.target.value)} required/><Input label="Unidade" value={form.unit??'un'} onChange={e=>field('unit',e.target.value)} required/><Input label="Quantidade" type="number" min="0" step="0.01" value={form.quantity??''} onChange={e=>field('quantity',e.target.value)} required/><Input label="Valor unitário" type="number" min="0" step="0.01" value={form.unitPrice??''} onChange={e=>field('unitPrice',e.target.value)} required/></div>;
  if(kind==='convert')content=<div className="engineering-form-grid"><Select label="Provisório" value={form.provisionalId??''} onChange={e=>field('provisionalId',e.target.value)} options={provisionalOptions} required/><Select label="Converter em" value={form.destination??'contract'} onChange={e=>field('destination',e.target.value)} options={[{value:'contract',label:'Contrato'},{value:'addendum',label:'Aditivo'}]}/><Input label="Número de destino" value={form.number??''} onChange={e=>field('number',e.target.value)} required/>{form.destination==='addendum'&&<><Select label="Contrato" value={form.contractId??''} onChange={e=>field('contractId',e.target.value)} options={contractOptions} required/><Select label="Tipo" value={form.addendumType??'increase'} onChange={e=>field('addendumType',e.target.value)} options={[{value:'increase',label:'Acréscimo'},{value:'reduction',label:'Redução'},{value:'adjustment',label:'Ajuste'}]}/></>}</div>;
  if(kind==='addendum')content=<div className="engineering-form-grid"><Select label="Contrato" value={form.contractId??''} onChange={e=>field('contractId',e.target.value)} options={contractOptions} required/><Input label="Número" value={form.number??''} onChange={e=>field('number',e.target.value)} required/><Select label="Tipo" value={form.type??'increase'} onChange={e=>field('type',e.target.value)} options={[{value:'increase',label:'Acréscimo'},{value:'reduction',label:'Redução'},{value:'adjustment',label:'Ajuste'}]}/><Input label="Vigência" type="date" value={form.effectiveDate??today()} onChange={e=>field('effectiveDate',e.target.value)}/><Input label="Valor declarado" type="number" min="0" step="0.01" value={form.statedValue??''} onChange={e=>field('statedValue',e.target.value)}/></div>;
  if(kind==='addendumLine')content=<div className="engineering-form-grid"><Select label="Aditivo" value={form.addendumId??''} onChange={e=>{const a=data?.addenda.find(i=>i.id===e.target.value);field('addendumId',e.target.value);field('contractId',a?.contractId??'');}} options={addendumOptions} required/><Select label="Serviço do contrato" value={form.contractServiceId??''} onChange={e=>{const s=data?.contractServices.find(i=>i.id===e.target.value);field('contractServiceId',e.target.value);if(s){field('description',s.description);field('unit',s.unit);field('unitPrice',String(s.unitPrice));}}} options={contractServiceOptions}/><Select label="Serviço novo" value={form.serviceId??''} onChange={e=>{const s=data?.services.find(i=>i.id===e.target.value);field('serviceId',e.target.value);if(s){field('description',s.name);field('unit',s.unit);}}} options={serviceOptions}/><Input label="Descrição" value={form.description??''} onChange={e=>field('description',e.target.value)} required/><Input label="Unidade" value={form.unit??'un'} onChange={e=>field('unit',e.target.value)} required/><Input label="Variação quantidade (+/-)" type="number" step="0.01" value={form.quantityDelta??''} onChange={e=>field('quantityDelta',e.target.value)} required/><Input label="Valor unitário" type="number" min="0" step="0.01" value={form.unitPrice??''} onChange={e=>field('unitPrice',e.target.value)} required/></div>;
  if(kind==='measurement')content=<div className="engineering-form-grid"><Select label="Contrato" value={form.contractId??''} onChange={e=>field('contractId',e.target.value)} options={contractOptions} required/><Input label="Competência" type="month" value={form.competence??currentMonth()} onChange={e=>field('competence',e.target.value)} required/></div>;
  if(kind==='measurementLine')content=<div className="engineering-form-grid"><Select label="Medição" value={form.measurementId??''} onChange={e=>{const m=data?.measurements.find(i=>i.id===e.target.value);field('measurementId',e.target.value);field('contractId',m?.contractId??'');}} options={measurementOptions} required/><Select label="Serviço do contrato" value={form.contractServiceId??''} onChange={e=>{const s=data?.contractServices.find(i=>i.id===e.target.value);field('contractServiceId',e.target.value);if(s)field('unitPrice',String(s.unitPrice));}} options={contractServiceOptions} required/><Select label="Estrutura" value={form.structureId??''} onChange={e=>field('structureId',e.target.value)} options={opts(data?.structures??[])}/><Input label="Quantidade medida" type="number" min="0.01" step="0.01" value={form.measuredQuantity??''} onChange={e=>field('measuredQuantity',e.target.value)} required/><Input label="Valor unitário" type="number" min="0" step="0.01" value={form.unitPrice??''} onChange={e=>field('unitPrice',e.target.value)} required/></div>;
  if(kind==='retention')content=<div className="engineering-form-grid"><Select label="Medição" value={form.measurementId??''} onChange={e=>field('measurementId',e.target.value)} options={measurementOptions} required/><Select label="Retenção" value={form.retentionType??'inss'} onChange={e=>field('retentionType',e.target.value)} options={[{value:'inss',label:'INSS'},{value:'iss',label:'ISS'},{value:'rt',label:'RT'},{value:'other',label:'Outra'}]}/><Select label="Cálculo" value={form.calculationType??'percentage'} onChange={e=>field('calculationType',e.target.value)} options={[{value:'percentage',label:'Percentual'},{value:'fixed',label:'Valor fixo'}]}/>{form.calculationType==='fixed'?<Input label="Valor" type="number" min="0" step="0.01" value={form.fixedAmount??''} onChange={e=>field('fixedAmount',e.target.value)} required/>:<Input label="Percentual" type="number" min="0" step="0.01" value={form.rate??''} onChange={e=>field('rate',e.target.value)} required/>}</div>;
  if(kind==='measurementStatus')content=<div className="engineering-form-grid"><Select label="Medição" value={form.measurementId??''} onChange={e=>field('measurementId',e.target.value)} options={measurementOptions} required/><Select label="Ação" value={form.action??'close'} onChange={e=>field('action',e.target.value)} options={[{value:'close',label:'Fechar'},{value:'approve',label:'Aprovar'},{value:'reopen',label:'Reabrir'},{value:'cancel',label:'Cancelar'}]}/><Input label="Motivo" value={form.reason??''} onChange={e=>field('reason',e.target.value)}/></div>;
  if(kind==='receivable')content=<div className="engineering-form-grid"><Select label="Medição" value={form.measurementId??''} onChange={e=>field('measurementId',e.target.value)} options={measurementOptions} required/><Input label="Vencimento" type="date" value={form.dueDate??today()} onChange={e=>field('dueDate',e.target.value)} required/></div>;
  if(kind==='receive')content=<div className="engineering-form-grid"><Select label="Medição" value={form.measurementId??''} onChange={e=>field('measurementId',e.target.value)} options={measurementOptions} required/><Select label="Conta" value={form.accountId??''} onChange={e=>field('accountId',e.target.value)} options={accountOptions} required/><Input label="Recebido em" type="date" value={form.receivedOn??today()} onChange={e=>field('receivedOn',e.target.value)} required/><Input label="Valor" type="number" min="0.01" step="0.01" value={form.amount??''} onChange={e=>field('amount',e.target.value)} required/></div>;
  if(kind==='productionPeriod')content=<div className="engineering-form-grid"><Select label="Obra" value={form.workId??''} onChange={e=>field('workId',e.target.value)} options={workOptions} required/><Input label="Competência" type="month" value={form.competence??currentMonth()} onChange={e=>field('competence',e.target.value)} required/></div>;
  if(kind==='productionEntry')content=<div className="engineering-form-grid"><Select label="Período" value={form.periodId??''} onChange={e=>{field('periodId',e.target.value);field('structureId','');}} options={periodOptions} required/><Select label="Colaborador" value={form.employmentContractId??''} onChange={e=>field('employmentContractId',e.target.value)} options={employeeOptions} required/><Select label="Estrutura" value={form.structureId??''} onChange={e=>field('structureId',e.target.value)} options={structureOptions} required/><Select label="Serviço" value={form.serviceId??''} onChange={e=>field('serviceId',e.target.value)} options={serviceOptions} required/><Input label="Data" type="date" value={form.productionDate??today()} onChange={e=>field('productionDate',e.target.value)} required/><Input label="Quantidade" type="number" min="0.01" step="0.01" value={form.executedQuantity??''} onChange={e=>field('executedQuantity',e.target.value)} required/><Input label="Valor unitário" type="number" min="0" step="0.01" value={form.unitValue??''} onChange={e=>field('unitValue',e.target.value)}/></div>;
  if(kind==='productionStatus')content=<div className="engineering-form-grid"><Select label="Período" value={form.periodId??''} onChange={e=>field('periodId',e.target.value)} options={periodOptions} required/><Select label="Ação" value={form.action??'close'} onChange={e=>field('action',e.target.value)} options={[{value:'close',label:'Fechar'},{value:'reopen',label:'Reabrir'}]}/><Input label="Motivo" value={form.reason??''} onChange={e=>field('reason',e.target.value)}/></div>;

  return <><div className="engineering-actions">{actions[activeTab]}</div>{operations.state.errorMessage&&kind===null&&<Feedback tone="danger" title="Operação não concluída" message={operations.state.errorMessage}/>} {operations.state.successMessage&&kind===null&&<Feedback tone="success" title="Concluído" message={operations.state.successMessage}/>}<Dialog open={kind!==null} title={kind?title[kind]:'Engenharia'} description="Operação vinculada exclusivamente à empresa selecionada." loading={operations.state.busy} onClose={close} onBack={close} onConfirm={kind?()=>{void submit();}:undefined}>{operations.state.errorMessage&&<Feedback tone="danger" title="Não foi possível salvar" message={operations.state.errorMessage}/>} {content}</Dialog></>;
}
