import { useEffect, useMemo, useState } from 'react';
import type { CompanySummary } from '../../platform/domain/AccessContext';
import { Button } from '../../../shared/ui/Button';
import { Dialog } from '../../../shared/ui/Dialog';
import { Feedback, LoadingState } from '../../../shared/ui/Feedback';
import { Input } from '../../../shared/ui/Input';
import { Select } from '../../../shared/ui/Select';
import { getSupabaseClient } from '../../../shared/infrastructure/supabase/client';
import type { CreditCard } from '../domain/cards';
import type { FinancialAccount } from '../domain/registries';
import { getFinanceRepositories } from '../infrastructure/createFinanceRepositories';
import { useFinanceOperations } from './useFinanceOperations';
import './quick-entry.css';

type EntryType = 'expense' | 'income';
type LaunchType = 'single' | 'installment' | 'recurring';
type PaymentMethod = 'pix' | 'debit' | 'credit' | 'cash' | 'transfer' | 'boleto' | 'other';
type InlineRegistry = 'costCenter' | 'category';
type OwnedAccount = FinancialAccount & { ownerLabel: string };
type OwnedCard = CreditCard & { ownerLabel: string };
type SmartTemplate = { description:string; companyId:string; entryType:EntryType; categoryId:string; costCenterId:string; accountRef:string; paymentMethod:PaymentMethod; cardRef:string; occurredOn:string };
interface QuickEntryDialogProps { open:boolean; companies:readonly CompanySummary[]; initialCompanyId?:string; allCompaniesMode?:boolean; onClose:()=>void }
const today=()=>new Date().toISOString().slice(0,10); const monthStart=(v:string)=>`${v.slice(0,7)}-01`; const idempotencyKey=(p:string)=>`${p}:${crypto.randomUUID()}`;
const digitsOnly=(v:string)=>v.replace(/\D/g,'').slice(0,14); const amountFromDigits=(d:string)=>Number(d||'0')/100; const formatMoneyDigits=(d:string)=>d?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(amountFromDigits(d)):'';
const normalized=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLocaleLowerCase('pt-BR'); const paymentRef=(c:string,r:string)=>`${c}::${r}`;
function parsePaymentRef(v:string){const s=v.indexOf('::');return s<=0?null:{companyId:v.slice(0,s),resourceId:v.slice(s+2)}}
function companyName(c:CompanySummary){const r=`${c.tradeName??''} ${c.legalName}`.toUpperCase();if(r.includes('PESSOAL'))return'Pessoal';if(r.includes('PR'))return'PR';if(r.includes('CR'))return'CR';return c.tradeName??c.legalName}
const COST_CENTER_ORDER=['Admin','Blaze','CR','Pessoal','PR','Sartori'] as const;
function costCenterLabel(code:string|null,name:string){const r=`${code??''} ${name}`.toUpperCase();if(r.includes('ADMIN'))return'Admin';if(r.includes('BLAZE'))return'Blaze';if(r.includes('PESSOAL'))return'Pessoal';if(r.includes('SARTORI'))return'Sartori';if(r.includes('CR-HIST')||/(^|\s)CR(\s|$)/.test(r))return'CR';if(r.includes('PR-HIST')||/(^|\s)PR(\s|$)/.test(r))return'PR';return null}
function canonicalCostCenters<T extends {id:string;code:string|null;name:string}>(rows:readonly T[]){const chosen=new Map<string,T>(),extras:T[]=[];for(const item of rows){const label=costCenterLabel(item.code,item.name);if(!label){extras.push(item);continue}const cur=chosen.get(label),ch=cur?/HIST/i.test(`${cur.code??''} ${cur.name}`):true,nh=/HIST/i.test(`${item.code??''} ${item.name}`);if(!cur||(ch&&!nh))chosen.set(label,item)}return[...COST_CENTER_ORDER.flatMap(label=>chosen.get(label)?[{item:chosen.get(label)!,label}]:[]),...extras.sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')).map(item=>({item,label:item.name}))]}
function recurrenceEnd(start:string,count:number){const d=new Date(`${start}T12:00:00`);d.setMonth(d.getMonth()+Math.max(0,count-1));return d.toISOString().slice(0,10)}
export function QuickEntryDialog({open,companies,initialCompanyId='',allCompaniesMode=false,onClose}:QuickEntryDialogProps){
 const [companyId,setCompanyId]=useState(initialCompanyId||companies[0]?.id||''),[moreOptions,setMoreOptions]=useState(false),[inlineRegistry,setInlineRegistry]=useState<InlineRegistry|null>(null),[newRegistryName,setNewRegistryName]=useState(''),[templates,setTemplates]=useState<readonly SmartTemplate[]>([]),[lastSuggestedDescription,setLastSuggestedDescription]=useState(''),[paymentAccounts,setPaymentAccounts]=useState<readonly OwnedAccount[]>([]),[paymentCards,setPaymentCards]=useState<readonly OwnedCard[]>([]),[paymentLoading,setPaymentLoading]=useState(false),[submitting,setSubmitting]=useState(false),[localError,setLocalError]=useState<string|null>(null),[localSuccess,setLocalSuccess]=useState<string|null>(null);
 const [form,setForm]=useState({entryType:'expense' as EntryType,date:today(),description:'',amountDigits:'',paymentMethod:'pix' as PaymentMethod,launchType:'single' as LaunchType,installmentCount:'2',recurrenceCount:'12',accountRef:'',cardRef:'',categoryId:'',costCenterId:'',counterparty:'',notes:''});
 useEffect(()=>{if(!open)return;setCompanyId(initialCompanyId||companies[0]?.id||'');setMoreOptions(false);setLastSuggestedDescription('');setInlineRegistry(null);setNewRegistryName('');setLocalError(null);setLocalSuccess(null);setForm({entryType:'expense',date:today(),description:'',amountDigits:'',paymentMethod:'pix',launchType:'single',installmentCount:'2',recurrenceCount:'12',accountRef:'',cardRef:'',categoryId:'',costCenterId:'',counterparty:'',notes:''})},[companies,initialCompanyId,open]);
 const company=companies.find(i=>i.id===companyId)??companies[0]; const scope=useMemo(()=>({tenantId:company?.tenantId??'',companyId:company?.id??''}),[company?.id,company?.tenantId]); const operations=useFinanceOperations(scope); const references=operations.state.references;
 useEffect(()=>{if(!open||!companies.length)return;let cancelled=false;setPaymentLoading(true);void(async()=>{const repos=getFinanceRepositories(),source=allCompaniesMode?companies:company?[company]:[];const rows=await Promise.all(source.map(async owner=>{const s={tenantId:owner.tenantId,companyId:owner.id};const[a,c]=await Promise.all([repos.registries.listAccounts(s),repos.cards.listCards(s)]);return{accounts:a.filter(i=>i.status==='active').map(i=>({...i,ownerLabel:companyName(owner)})),cards:c.filter(i=>i.status==='active').map(i=>({...i,ownerLabel:companyName(owner)}))}}));if(!cancelled){setPaymentAccounts(rows.flatMap(i=>i.accounts));setPaymentCards(rows.flatMap(i=>i.cards));setPaymentLoading(false)}})().catch(()=>{if(!cancelled){setPaymentAccounts([]);setPaymentCards([]);setPaymentLoading(false)}});return()=>{cancelled=true}},[allCompaniesMode,companies,company,open]);
 useEffect(()=>{if(!open||!companies.length)return;let cancelled=false;void(async()=>{const repos=getFinanceRepositories();const lists=await Promise.all(companies.map(async c=>(await repos.entries.list({tenantId:c.tenantId,companyId:c.id})).map(r=>({description:r.description,companyId:c.id,entryType:r.entryType,categoryId:r.categoryId,costCenterId:r.costCenterId??'',accountRef:r.plannedAccountId?paymentRef(c.id,r.plannedAccountId):'',paymentMethod:'pix' as PaymentMethod,cardRef:'',occurredOn:r.dueDate}))));const cardTemplates:SmartTemplate[]=[];const tenantId=companies[0]?.tenantId;if(tenantId){const{data}=await getSupabaseClient().from('card_transactions').select('company_id,expense_company_id,card_id,purchase_date,description,category_id,cost_center_id').eq('tenant_id',tenantId).order('purchase_date',{ascending:false}).limit(200);for(const r of data??[])cardTemplates.push({description:String(r.description??''),companyId:String(r.expense_company_id??r.company_id??''),entryType:'expense',categoryId:String(r.category_id??''),costCenterId:r.cost_center_id?String(r.cost_center_id):'',accountRef:'',paymentMethod:'credit',cardRef:paymentRef(String(r.company_id??''),String(r.card_id??'')),occurredOn:String(r.purchase_date??'')})}if(!cancelled)setTemplates([...cardTemplates,...lists.flat()].sort((a,b)=>b.occurredOn.localeCompare(a.occurredOn)))})().catch(()=>{if(!cancelled)setTemplates([])});return()=>{cancelled=true}},[companies,open]);
 const active=(references?.costCenters??[]).filter(i=>i.status==='active'),categories=(references?.categories??[]).filter(i=>i.status==='active'&&(i.kind==='both'||i.kind===form.entryType)),costCenters=canonicalCostCenters(active);
 const companyOptions=companies.map(i=>({value:i.id,label:companyName(i)})),accountOptions=[{value:'',label:'Selecione'},...paymentAccounts.map(i=>({value:paymentRef(i.companyId,i.id),label:i.name}))],cardOptions=[{value:'',label:'Selecione o cartão'},...paymentCards.map(i=>({value:paymentRef(i.companyId,i.id),label:i.name}))],categoryOptions=[{value:'',label:'Selecione'},...categories.map(i=>({value:i.id,label:i.name}))],costCenterOptions=[{value:'',label:'Selecione'},...costCenters.map(({item,label})=>({value:item.id,label}))];
 const paymentOptions=[{value:'pix',label:'Pix'},{value:'debit',label:'Cartão de débito'},...(form.entryType==='expense'?[{value:'credit',label:'Cartão de crédito'}]:[]),{value:'cash',label:'Dinheiro'},{value:'transfer',label:'Transferência'},{value:'boleto',label:'Boleto'},{value:'other',label:'Outro'}],launchOptions=[{value:'single',label:'Único / à vista'},{value:'installment',label:'Parcelado'},...(form.paymentMethod==='credit'?[]:[{value:'recurring',label:'Recorrente'}])];
 function set<K extends keyof typeof form>(f:K,v:(typeof form)[K]){setForm(c=>({...c,[f]:v}))} function setPaymentMethod(v:PaymentMethod){setForm(c=>({...c,paymentMethod:v,launchType:v==='credit'&&c.launchType==='recurring'?'single':c.launchType,accountRef:v==='credit'?'':c.accountRef,cardRef:v==='credit'?c.cardRef:''}))}
 function smartFill(description:string){const q=normalized(description);if(q.length<3){set('description',description);return}const match=templates.find(i=>(normalized(i.description)===q||normalized(i.description).includes(q))&&(allCompaniesMode||i.companyId===companyId));if(!match){set('description',description);return}setLastSuggestedDescription(q);if(allCompaniesMode)setCompanyId(match.companyId);setForm(c=>({...c,description,entryType:match.entryType,categoryId:match.categoryId,costCenterId:match.costCenterId,accountRef:match.accountRef,paymentMethod:match.paymentMethod,cardRef:match.cardRef,launchType:'single'}))}
 function resetAfterSave(keepData:boolean){setLastSuggestedDescription('');setLocalSuccess(null);setForm(c=>keepData?{...c,date:today(),description:'',amountDigits:'',counterparty:'',notes:''}:{entryType:'expense',date:today(),description:'',amountDigits:'',paymentMethod:'pix',launchType:'single',installmentCount:'2',recurrenceCount:'12',accountRef:'',cardRef:'',categoryId:'',costCenterId:'',counterparty:'',notes:''})}
 async function createInlineRegistry(kind:InlineRegistry){const name=newRegistryName.trim();if(!name||!company)return;operations.clearFeedback();setLocalError(null);try{if(kind==='category'){const created=await operations.createCategory({name,kind:form.entryType});await operations.loadReferences();set('categoryId',created.id)}else{const created=await operations.createCostCenter({name,code:null});await operations.loadReferences();set('costCenterId',created.id)}setInlineRegistry(null);setNewRegistryName('')}catch(e){setLocalError(e instanceof Error&&e.message?e.message:'Não foi possível concluir o cadastro rápido.')}}
 async function launch(keepData:boolean){operations.clearFeedback();setLocalError(null);setLocalSuccess(null);const amount=amountFromDigits(form.amountDigits);if(!company||!form.description.trim()||!Number.isFinite(amount)||amount<=0||!form.categoryId){setLocalError('Preencha descrição, valor e categoria.');return}if(form.paymentMethod==='credit'&&(!form.cardRef||form.entryType!=='expense')){setLocalError('Selecione um cartão válido.');return}setSubmitting(true);try{if(form.launchType==='recurring'){const count=Math.max(1,Math.trunc(Number(form.recurrenceCount||'1')));await operations.createRecurrence({entryType:form.entryType,description:form.description.trim(),counterpartyName:form.counterparty.trim()||null,categoryId:form.categoryId,costCenterId:form.costCenterId||null,amount,frequency:'monthly',intervalCount:1,startDate:form.date,endDate:recurrenceEnd(form.date,count),notes:form.notes.trim()||null})}else if(form.paymentMethod==='credit'){const card=parsePaymentRef(form.cardRef);if(!card)throw new Error('Selecione um cartão válido.');const result=await getSupabaseClient().rpc('create_card_purchase_cross_company',{p_tenant_id:company.tenantId,p_card_company_id:card.companyId,p_expense_company_id:company.id,p_card_id:card.resourceId,p_purchase_date:form.date,p_description:form.description.trim(),p_counterparty_name:form.counterparty.trim()||null,p_category_id:form.categoryId,p_cost_center_id:form.costCenterId||null,p_total_amount:amount,p_installment_count:form.launchType==='installment'?Math.max(2,Math.trunc(Number(form.installmentCount||'2'))):1,p_idempotency_key:idempotencyKey('quick-card-purchase'),p_notes:form.notes.trim()||null});if(result.error)throw result.error}else{const created=await operations.createEntry({entryType:form.entryType,description:form.description.trim(),counterpartyName:form.counterparty.trim()||null,categoryId:form.categoryId,costCenterId:form.costCenterId||null,competenceMonth:monthStart(form.date),dueDate:form.date,amount,installmentCount:form.launchType==='installment'?Math.max(2,Math.trunc(Number(form.installmentCount||'2'))):1,notes:form.notes.trim()||null});const account=parsePaymentRef(form.accountRef);if(account)await getFinanceRepositories().entries.setPlannedAccount(scope,created.entryId,account.resourceId,account.companyId)}await operations.loadReferences();resetAfterSave(keepData);setLocalSuccess(keepData?'Lançamento concluído. Dados principais mantidos.':'Lançamento concluído.')}catch(e){setLocalError(e instanceof Error&&e.message?e.message:'Não foi possível concluir o lançamento.')}finally{setSubmitting(false)}}
 const busy=operations.state.busy||paymentLoading||submitting;const footer=<div className="quick-entry__footer-actions"><Button variant="secondary" disabled={busy} onClick={()=>void launch(true)}>Lançar e manter dados</Button><Button loading={busy} loadingLabel="Lançando…" onClick={()=>void launch(false)}>Lançar</Button></div>;
 return <Dialog open={open} title="Novo lançamento" onClose={onClose} onBack={onClose} loading={busy} footer={footer}>{!company?<Feedback tone="danger" title="Empresa obrigatória" message="Selecione uma empresa para continuar."/>:!references&&operations.state.busy?<LoadingState label="Carregando dados do lançamento…"/>:<>{(localError??operations.state.errorMessage)&&<Feedback tone="danger" title="Não foi possível lançar" message={localError??operations.state.errorMessage??''}/>} {(localSuccess??operations.state.successMessage)&&<Feedback tone="success" title="Lançamento concluído" message={localSuccess??operations.state.successMessage??''}/>}<div className="quick-entry"><div className="quick-entry__step"><span>1</span><strong>Dados principais</strong></div><div className="quick-entry__grid">
 <Select label="Tipo" value={form.entryType} onChange={e=>set('entryType',e.target.value as EntryType)} options={[{value:'expense',label:'Despesa'},{value:'income',label:'Receita'}]}/><Input label="Data" type="date" value={form.date} onChange={e=>set('date',e.target.value)} required/><Input label="Descrição" placeholder="Ex.: Café da manhã" value={form.description} onChange={e=>smartFill(e.target.value)} required/><Input label="Valor" inputMode="numeric" placeholder="R$ 0,00" value={formatMoneyDigits(form.amountDigits)} onChange={e=>set('amountDigits',digitsOnly(e.target.value))} required/><Select label="Forma de pagamento" value={form.paymentMethod} onChange={e=>setPaymentMethod(e.target.value as PaymentMethod)} options={paymentOptions}/><Select label="Tipo de lançamento" value={form.launchType} onChange={e=>set('launchType',e.target.value as LaunchType)} options={launchOptions}/>{form.launchType==='installment'&&<Input label="Quantidade de parcelas" type="number" min="2" max="120" value={form.installmentCount} onChange={e=>set('installmentCount',e.target.value)} required/>}{form.launchType==='recurring'&&<Input label="Quantidade de repetições" type="number" min="1" max="120" value={form.recurrenceCount} onChange={e=>set('recurrenceCount',e.target.value)} required/>}{form.paymentMethod==='credit'?<Select label="Cartão" value={form.cardRef} onChange={e=>set('cardRef',e.target.value)} options={cardOptions} required/>:<Select label="Banco" value={form.accountRef} onChange={e=>set('accountRef',e.target.value)} options={accountOptions}/>} {companies.length>1?<Select label="Empresa" value={companyId} options={companyOptions} onChange={e=>{setCompanyId(e.target.value);setForm(c=>({...c,categoryId:'',costCenterId:'',accountRef:allCompaniesMode?c.accountRef:'',cardRef:allCompaniesMode?c.cardRef:''}))}}/>:<Input label="Empresa" value={companyName(company)} disabled/>}
 <div className="quick-entry__registry-field"><div className="quick-entry__registry-control"><Select label="Obra / Centro de custo" value={form.costCenterId} onChange={e=>set('costCenterId',e.target.value)} options={costCenterOptions}/><Button className="quick-entry__add" aria-label="Adicionar obra ou centro de custo" onClick={()=>{setInlineRegistry(inlineRegistry==='costCenter'?null:'costCenter');setNewRegistryName('')}}>＋</Button></div>{inlineRegistry==='costCenter'&&<div className="quick-entry__registry-create"><Input label="Nova obra / centro de custo" value={newRegistryName} onChange={e=>setNewRegistryName(e.target.value)}/><Button disabled={busy||!newRegistryName.trim()} onClick={()=>void createInlineRegistry('costCenter')}>Adicionar</Button></div>}</div>
 <div className="quick-entry__registry-field"><div className="quick-entry__registry-control"><Select label="Categoria" value={form.categoryId} onChange={e=>set('categoryId',e.target.value)} options={categoryOptions} required/><Button className="quick-entry__add" aria-label="Adicionar categoria" onClick={()=>{setInlineRegistry(inlineRegistry==='category'?null:'category');setNewRegistryName('')}}>＋</Button></div>{inlineRegistry==='category'&&<div className="quick-entry__registry-create"><Input label="Nova categoria" value={newRegistryName} onChange={e=>setNewRegistryName(e.target.value)}/><Button disabled={busy||!newRegistryName.trim()} onClick={()=>void createInlineRegistry('category')}>Adicionar</Button></div>}</div></div>
 <Button className="quick-entry__more" variant="secondary" onClick={()=>setMoreOptions(v=>!v)} aria-expanded={moreOptions}>{moreOptions?'⌃ Menos opções':'⌄ Mais opções'}</Button>{moreOptions&&<><div className="quick-entry__step quick-entry__step--secondary"><span>2</span><strong>Detalhes adicionais</strong></div><div className="quick-entry__more-grid"><Input label={form.entryType==='expense'?'Fornecedor / beneficiário':'Pagador / origem'} value={form.counterparty} onChange={e=>set('counterparty',e.target.value)}/><Input label="Observação" value={form.notes} onChange={e=>set('notes',e.target.value)}/></div></>}</div></>}</Dialog>;
}