import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { CompanySummary } from '../../platform/domain/AccessContext';
import { Button } from '../../../shared/ui/Button';
import { Card } from '../../../shared/ui/Card';
import { EmptyState, LoadingState } from '../../../shared/ui/Feedback';
import { useHomeOverview } from './useHomeOverview';
import './home.css';
interface HomePageProps { companies: readonly CompanySummary[]; }
const currency=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}); const money=(v:number)=>currency.format(v); const sum=(v:readonly number[])=>v.reduce((t,n)=>t+n,0); const isoDate=(v:Date)=>v.toISOString().slice(0,10);
function polyline(values:readonly number[],width=620,height=145){const min=Math.min(0,...values),max=Math.max(0,...values),range=Math.max(1,max-min);return values.map((v,i)=>`${((i/Math.max(1,values.length-1))*width).toFixed(1)},${(height-((v-min)/range)*height).toFixed(1)}`).join(' ');}
const periods=[{days:7,label:'7 dias'},{days:15,label:'15 dias'},{days:30,label:'30 dias'},{days:90,label:'90 dias'},{days:365,label:'1 ano'}] as const;
export function HomePage({companies}:HomePageProps){
 const navigate=useNavigate(); const go=(path:string)=>{void navigate(path);}; const [chartDays,setChartDays]=useState<number>(30); const overview=useHomeOverview(companies);
 if(overview.status==='idle'||overview.status==='loading')return <LoadingState label="Carregando painel…"/>; if(overview.status==='error')return <EmptyState title="Painel indisponível" message={overview.errorMessage}/>; if(!overview.data)return <EmptyState title="Painel indisponível" message="Os dados da visão consolidada ainda não estão disponíveis."/>;
 const data=overview.data,today=isoDate(new Date()); const rangeDates=Array.from({length:chartDays},(_,offset)=>{const d=new Date();d.setDate(d.getDate()-(chartDays-1-offset));return isoDate(d);}); const movementByDate=new Map<string,number>(); data.balanceMovements.forEach(i=>movementByDate.set(i.movementOn,(movementByDate.get(i.movementOn)??0)+i.signedAmount)); const rangeTotal=sum(rangeDates.map(d=>movementByDate.get(d)??0)); let running=data.bankBalance-rangeTotal; const series=rangeDates.map(d=>{running+=movementByDate.get(d)??0;return running;});
 const dueToday=data.entries.filter(i=>i.dueDate===today&&i.entryType==='expense'),receiveToday=data.entries.filter(i=>i.dueDate===today&&i.entryType==='income'),overdue=data.entries.filter(i=>i.dueDate<today&&i.entryType==='expense'); const limit=new Date();limit.setDate(limit.getDate()+7);const next7=data.entries.filter(i=>i.dueDate>today&&i.dueDate<=isoDate(limit)&&i.entryType==='expense'); const todayResult=sum(receiveToday.map(i=>i.amount))-sum(dueToday.map(i=>i.amount)); const budgets=data.budgets.slice(0,6),accounts=data.bankAccounts.slice(0,6),cards=data.cards.slice(0,6),upcoming=[...data.entries].filter(i=>i.entryType==='expense'&&i.dueDate>=today).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,4),flowResult=data.incomeRealized-data.expenseRealized;
 return <section className="home-approved" aria-label="Painel inicial">
  <div className="home-hero"><div><strong>Olá! Bom dia</strong><span>{new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit'}).format(new Date())}</span></div><Button onClick={()=>window.location.reload()}>Atualizar</Button></div>
  <Card className="home-quick-card"><div className="home-actions"><Button onClick={()=>go('/financeiro?tab=lancamentos&action=new-entry')}>＋ Lançamento</Button><Button variant="secondary" onClick={()=>go('/contas-do-mes')}>▣ Contas do mês</Button></div></Card>
  <Card className="home-balance-card"><div className="balance-card"><span className="home-eyebrow">Saldo disponível</span><strong className="balance-card__value">{money(data.bankBalance)}</strong><div className="balance-chart-head"><strong>Evolução do saldo</strong><span>Últimos {chartDays===365?'12 meses':`${chartDays} dias`}</span></div><svg className="balance-chart" viewBox="0 0 620 145" role="img" aria-label={`Evolução real do saldo nos últimos ${chartDays} dias`}><g className="balance-chart__grid"><line x1="0" y1="36" x2="620" y2="36"/><line x1="0" y1="72" x2="620" y2="72"/><line x1="0" y1="108" x2="620" y2="108"/></g><polyline className="balance-chart__line" points={polyline(series)}/></svg><div className="balance-legend"><span>● Entradas</span><span>● Saídas</span><span>● Saldo</span></div><div className="balance-range">{periods.map(p=>chartDays===p.days?<Button key={p.days} size="sm" variant="secondary" aria-pressed="true" onClick={()=>setChartDays(p.days)}>{p.label}</Button>:<Button key={p.days} size="sm" aria-pressed="false" onClick={()=>setChartDays(p.days)}>{p.label}</Button>)}</div><div className="balance-card__footer"><span>Saldo atual</span><strong>{money(data.bankBalance)}</strong></div></div></Card>
  <div className="home-two-column"><Card title="Orçamento do mês" actions={<Button size="sm" onClick={()=>go('/rh?tab=orcamento&action=budget-plan')}>＋ Definir orçamento</Button>}><div className="budget-list">{budgets.length===0?<span className="ui-muted">Nenhum orçamento manual criado nesta competência.</span>:budgets.map(i=><button className="budget-tile" key={`${i.companyId}-${i.costCenterId??'geral'}`} onClick={()=>go('/rh?tab=orcamento')}><div><strong>{i.costCenterName??'Geral'}</strong><small>{i.companyName}</small></div><div><strong>{money(i.plannedTotal-i.realizedTotal)}</strong><small>disponível</small></div><span>›</span></button>)}</div></Card>
  <Card title="Resumo diário" actions={<Button size="sm" onClick={()=>go('/rh?tab=orcamento&action=budget-plan')}>▦ Planejar</Button>}><div className="daily-summary"><div><span>Saldo em contas</span><strong>{money(data.bankBalance)}</strong></div><div className="is-danger"><span>A pagar hoje</span><strong>{money(sum(dueToday.map(i=>i.amount)))}</strong></div><div className="is-success"><span>A receber hoje</span><strong>{money(sum(receiveToday.map(i=>i.amount)))}</strong></div><div className="is-danger"><span>Vencidas</span><strong>{money(sum(overdue.map(i=>i.amount)))}</strong></div><div className="is-info"><span>Próximos 7 dias</span><strong>{money(sum(next7.map(i=>i.amount)))}</strong></div><div className={todayResult<0?'is-danger':'is-success'}><span>Resultado do dia</span><strong>{money(todayResult)}</strong></div></div></Card></div>
  <div className="home-two-column"><Card><div className="section-head"><div><span>MOVIMENTAÇÃO</span><h2>Fluxo do mês</h2></div><Button variant="secondary" size="sm" onClick={()=>go('/financeiro?tab=resumo')}>Ver análise →</Button></div><div className="flow-grid"><div className="is-success"><span>Entradas</span><strong>{money(data.incomeRealized)}</strong></div><div className="is-danger"><span>Saídas</span><strong>{money(data.expenseRealized)}</strong></div><div className="flow-result"><span>Resultado</span><strong>{money(flowResult)}</strong></div></div></Card><Card><div className="section-head"><div><span>DISPONIBILIDADE</span><h2>Contas bancárias</h2></div><Button variant="secondary" size="sm" onClick={()=>go('/bancos')}>Ver todas →</Button></div><div className="bank-strip">{accounts.length===0?<span className="ui-muted">Nenhuma conta exibida no painel.</span>:accounts.map(a=><button key={`${a.companyId}-${a.accountId}`} className="bank-tile" onClick={()=>go('/bancos')}><span>▥</span><small>{a.name}</small><strong>{money(a.currentBalance)}</strong></button>)}</div></Card></div>
  <Card><div className="section-head"><div><span>PRÓXIMOS DIAS</span><h2>Vencimentos</h2></div><Button variant="secondary" size="sm" onClick={()=>go('/contas-do-mes')}>Ver todos →</Button></div><div className="due-grid">{upcoming.length===0?<span className="ui-muted">Nenhum vencimento próximo.</span>:upcoming.map(i=>{const d=new Date(`${i.dueDate}T12:00:00`);return <button key={`${i.companyName}-${i.installmentId}`} className="due-tile" onClick={()=>go('/contas-do-mes')}><div className="due-date"><strong>{d.getDate()}</strong><small>{d.toLocaleDateString('pt-BR',{month:'short'}).replace('.','').toUpperCase()}</small></div><div><strong>{i.description}</strong><small>{i.companyName}</small></div><b>{money(i.amount)}</b></button>;})}</div></Card>
  <div className="home-two-column"><Card><div className="section-head"><div><span>CRÉDITO</span><h2>Cartões</h2></div><Button variant="secondary" size="sm" onClick={()=>go('/financeiro?tab=cartoes')}>Ver todos →</Button></div>{cards.length===0?<div className="cards-empty">▤ <span>Nenhum cartão ativo para acompanhar.</span></div>:<div className="card-strip">{cards.map(c=>{const usage=c.creditLimit>0?Math.min(100,Math.max(0,(c.committedAmount/c.creditLimit)*100)):0;return <button key={`${c.companyId}-${c.cardId}`} className="credit-card-tile" onClick={()=>go('/financeiro?tab=cartoes')}><div className="credit-card-tile__head"><strong title={c.name}>{c.name}</strong><span>{Math.round(usage)}%</span></div><div className="credit-card-tile__row"><span>Limite</span><b>{money(c.creditLimit)}</b></div><div className="credit-card-tile__row"><span>Usado</span><b>{money(c.committedAmount)}</b></div><div className="credit-card-tile__row"><span>Disponível</span><b>{money(c.availableLimit)}</b></div><div className="credit-card-tile__bar"><span style={{width:`${usage}%`}}/></div></button>;})}</div>}</Card><Card><div className="section-head"><div><span>ATALHOS</span><h2>Ações rápidas</h2></div></div><div className="shortcut-list"><button onClick={()=>go('/contas-do-mes')}>▣ <span>Contas do mês</span><b>›</b></button><button onClick={()=>go('/engenharia')}>⊕ <span>Nova medição</span><b>›</b></button><button onClick={()=>go('/bancos')}>⇄ <span>Transferências</span><b>›</b></button><button onClick={()=>go('/financeiro?tab=resumo')}>▥ <span>Relatórios</span><b>›</b></button></div></Card></div>
 </section>;
}
