import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import type { CompanySummary } from '../../platform/domain/AccessContext';
import { Button } from '../../../shared/ui/Button';
import { Card } from '../../../shared/ui/Card';
import { Dialog } from '../../../shared/ui/Dialog';
import { EmptyState, Feedback, LoadingState } from '../../../shared/ui/Feedback';
import { Input } from '../../../shared/ui/Input';
import { MoneyInput } from '../../../shared/ui/MoneyInput';
import { Select } from '../../../shared/ui/Select';
import type {
  PersonalSettlement,
  PersonalSettlementDirection,
  PersonalSettlementItem,
  PersonalSettlementMovement,
  PersonalSettlementsSnapshot,
} from '../domain/personalSettlements';
import { getPersonalSettlementsRepository } from '../infrastructure/createPersonalSettlementsRepository';
import './personal-settlements.css';

interface Props{companies:readonly CompanySummary[]}
type DeleteTarget={kind:'settlement'|'item'|'movement';id:string;label:string}|null;
const currency=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const dateLabel=(value:string)=>{const[y,m,d]=value.slice(0,10).split('-');return y&&m&&d?`${d}/${m}/${y}`:value;};
const localToday=()=>{const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);};
const isPersonal=(company:CompanySummary)=>`${company.tradeName??''} ${company.legalName}`.toLocaleUpperCase('pt-BR').includes('PESSOAL');

export function PersonalSettlementsPage({companies}:Props){
  const personalCompany=companies.find(isPersonal)??null;
  const repository=useMemo(()=>getPersonalSettlementsRepository(),[]);
  const[snapshot,setSnapshot]=useState<PersonalSettlementsSnapshot|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);
  const[createOpen,setCreateOpen]=useState(false);const[detailId,setDetailId]=useState<string|null>(null);const[itemTarget,setItemTarget]=useState<PersonalSettlement|null>(null);const[editingItem,setEditingItem]=useState<PersonalSettlementItem|null>(null);const[movementTarget,setMovementTarget]=useState<PersonalSettlement|null>(null);const[editingMovement,setEditingMovement]=useState<PersonalSettlementMovement|null>(null);const[deleteTarget,setDeleteTarget]=useState<DeleteTarget>(null);
  const[personName,setPersonName]=useState('');const[direction,setDirection]=useState<PersonalSettlementDirection>('owes_me');const[startedOn,setStartedOn]=useState(localToday());const[description,setDescription]=useState('');const[amount,setAmount]=useState(0);const[notes,setNotes]=useState('');const[accountId,setAccountId]=useState('');
  const[itemDate,setItemDate]=useState(localToday());const[itemDescription,setItemDescription]=useState('');const[itemAmount,setItemAmount]=useState(0);const[itemNotes,setItemNotes]=useState('');const[itemAccountId,setItemAccountId]=useState('');
  const[movementDate,setMovementDate]=useState(localToday());const[movementAmount,setMovementAmount]=useState(0);const[movementNote,setMovementNote]=useState('');const[movementAccountId,setMovementAccountId]=useState('');

  const reload=useCallback(async()=>{if(!personalCompany){setLoading(false);return;}setLoading(true);setError(null);try{setSnapshot(await repository.load({tenantId:personalCompany.tenantId,companyId:personalCompany.id}));}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível carregar os acertos pessoais.');}finally{setLoading(false);}},[personalCompany,repository]);
  useEffect(()=>{void reload();},[reload]);
  const settlements=snapshot?.settlements??[];const items=snapshot?.items??[];const movements=snapshot?.movements??[];const accounts=snapshot?.accounts??[];
  const accountOptions=[{value:'',label:'Sem movimentar conta'},...accounts.map(account=>({value:account.id,label:`${account.name}${account.bankInstitution?` · ${account.bankInstitution}`:''} · ${currency.format(account.currentBalance)}`}))];
  const requiredAccountOptions=[{value:'',label:'Selecione uma conta'},...accounts.map(account=>({value:account.id,label:`${account.name}${account.bankInstitution?` · ${account.bankInstitution}`:''} · ${currency.format(account.currentBalance)}`}))];
  const rowItems=(id:string)=>items.filter(item=>item.settlementId===id);const rowMovements=(id:string)=>movements.filter(move=>move.settlementId===id);
  const summary=(row:PersonalSettlement)=>{const total=rowItems(row.id).reduce((sum,item)=>sum+item.amount,0);const paid=rowMovements(row.id).reduce((sum,move)=>sum+move.amount,0);const balance=Math.max(0,total-paid);return{total,paid,balance,status:balance<=0&&total>0?'settled':paid>0?'partial':'open'} as const;};
  const totals=settlements.reduce((acc,row)=>{const balance=summary(row).balance;if(row.direction==='i_owe')acc.owe+=balance;else acc.receive+=balance;return acc;},{owe:0,receive:0});
  const selected=detailId?settlements.find(row=>row.id===detailId)??null:null;

  function resetCreate(){setPersonName('');setDirection('owes_me');setStartedOn(localToday());setDescription('');setAmount(0);setNotes('');setAccountId('');}
  function openAddItem(row:PersonalSettlement){setEditingItem(null);setItemTarget(row);setItemDate(localToday());setItemDescription('');setItemAmount(0);setItemNotes('');setItemAccountId('');}
  function openEditItem(row:PersonalSettlement,item:PersonalSettlementItem){setDetailId(null);setItemTarget(row);setEditingItem(item);setItemDate(item.itemDate);setItemDescription(item.description);setItemAmount(item.amount);setItemNotes(item.notes??'');setItemAccountId(item.financialAccountId??'');}
  function openAddMovement(row:PersonalSettlement){setEditingMovement(null);setMovementTarget(row);setMovementDate(localToday());setMovementAmount(summary(row).balance);setMovementNote('');setMovementAccountId('');}
  function openEditMovement(row:PersonalSettlement,move:PersonalSettlementMovement){setDetailId(null);setMovementTarget(row);setEditingMovement(move);setMovementDate(move.movementDate);setMovementAmount(move.amount);setMovementNote(move.note??'');setMovementAccountId(move.financialAccountId??'');}
  async function run(action:()=>Promise<unknown>,success:string,after?:()=>void){setSaving(true);setError(null);setMessage(null);try{await action();after?.();await reload();setMessage(success);window.dispatchEvent(new CustomEvent('finance-data-changed'));}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível concluir a operação.');}finally{setSaving(false);}}
  async function submitCreate(event:FormEvent){event.preventDefault();if(!personalCompany)return;if(!personName.trim()||amount<=0){setError('Informe a pessoa e um valor maior que zero.');return;}await run(()=>repository.create({scope:{tenantId:personalCompany.tenantId,companyId:personalCompany.id},personName,direction,startedOn,description,amount,notes,accountId:accountId||null}),'Acerto criado com sucesso.',()=>{setCreateOpen(false);resetCreate();});}
  async function submitItem(event:FormEvent){event.preventDefault();if(!itemTarget||!itemDescription.trim()||itemAmount<=0){setError('Informe a descrição e um valor maior que zero.');return;}const payload={itemDate,description:itemDescription,amount:itemAmount,notes:itemNotes,accountId:itemAccountId||null};await run(()=>editingItem?repository.updateItem(editingItem.id,payload):repository.addItem({settlementId:itemTarget.id,...payload}),editingItem?'Item atualizado com sucesso.':'Item adicionado com sucesso.',()=>{setItemTarget(null);setEditingItem(null);});}
  async function submitMovement(event:FormEvent){event.preventDefault();if(!movementTarget||movementAmount<=0||!movementAccountId){setError('Informe um valor maior que zero e selecione a conta.');return;}const payload={movementDate,amount:movementAmount,note:movementNote,accountId:movementAccountId};await run(()=>editingMovement?repository.updateMovement(editingMovement.id,payload):repository.addMovement({settlementId:movementTarget.id,...payload}),editingMovement?'Pagamento/recebimento atualizado.':movementTarget.direction==='i_owe'?'Pagamento registrado.':'Recebimento registrado.',()=>{setMovementTarget(null);setEditingMovement(null);});}
  async function confirmDelete(){if(!deleteTarget)return;const current=deleteTarget;await run(()=>current.kind==='settlement'?repository.deleteSettlement(current.id):current.kind==='item'?repository.deleteItem(current.id):repository.deleteMovement(current.id),current.kind==='settlement'?'Acerto removido. O histórico bancário realizado foi preservado.':current.kind==='item'?'Item removido e saldo recalculado.':'Pagamento/recebimento removido e saldo recalculado.',()=>{setDeleteTarget(null);setDetailId(null);});}

  if(!personalCompany)return <EmptyState title="Área particular indisponível" message="A empresa Pessoal não está disponível para este usuário."/>;
  if(loading&&!snapshot)return <LoadingState label="Carregando acertos pessoais…"/>;
  return <section className="personal-settlements-v3" aria-labelledby="personal-settlements-title">
    <header className="personal-settlements-v3__header"><div><small>ÁREA PARTICULAR</small><h1 id="personal-settlements-title">Acertos pessoais</h1><p>Controle particular de valores a pagar e a receber por pessoa.</p></div><Button onClick={()=>{resetCreate();setCreateOpen(true);}}>＋ Nova pessoa</Button></header>
    {error&&<Feedback title="Não foi possível concluir" message={error} tone="danger"/>}{message&&<Feedback title="Concluído" message={message} tone="success"/>}
    <div className="personal-settlements-v3__kpis"><Card title="Eu devo"><strong>{currency.format(totals.owe)}</strong><span>Saldo pendente</span></Card><Card title="Devem para mim"><strong>{currency.format(totals.receive)}</strong><span>Saldo a receber</span></Card><Card title="Saldo líquido"><strong>{currency.format(totals.receive-totals.owe)}</strong><span>A receber menos a pagar</span></Card></div>
    <Card title="Pessoas e saldos" description={`${settlements.length} pessoa(s) cadastrada(s).`}>
      {loading?<LoadingState/>:settlements.length===0?<EmptyState title="Nenhum acerto cadastrado" message="Cadastre uma pessoa para iniciar o controle."/>:<div className="personal-settlements-v3__grid">{settlements.map(row=>{const current=summary(row);const ownItems=rowItems(row.id);return <article key={row.id} className={`personal-settlements-v3__person personal-settlements-v3__person--${row.direction} personal-settlements-v3__person--${current.status}`}><header><div><strong>{row.personName}</strong><span>{row.direction==='i_owe'?'Eu devo':'A pessoa me deve'}</span></div><b>{current.status==='settled'?'Quitado':current.status==='partial'?'Parcial':'Em aberto'}</b></header><div className="personal-settlements-v3__items"><div><strong>Itens do acerto</strong><span>{ownItems.length} item(ns)</span></div>{ownItems.slice(0,3).map(item=><button type="button" key={item.id} className="personal-settlements-v3__item" onClick={()=>openEditItem(row,item)}><span><strong>{item.description}</strong><small>{dateLabel(item.itemDate)}</small></span><b>{currency.format(item.amount)}</b></button>)}{ownItems.length>3&&<small>+ {ownItems.length-3} item(ns) no histórico</small>}</div><dl><div><dt>Total</dt><dd>{currency.format(current.total)}</dd></div><div><dt>Abatido</dt><dd>{currency.format(current.paid)}</dd></div><div><dt>Saldo</dt><dd>{currency.format(current.balance)}</dd></div></dl><footer>{current.balance>0&&<Button onClick={()=>openAddMovement(row)}>{row.direction==='i_owe'?'Registrar pagamento':'Registrar recebimento'}</Button>}<div><Button variant="secondary" onClick={()=>openAddItem(row)}>＋ Item</Button><Button variant="secondary" onClick={()=>setDetailId(row.id)}>Abrir</Button><Button variant="danger" onClick={()=>setDeleteTarget({kind:'settlement',id:row.id,label:row.personName})}>Excluir</Button></div></footer></article>;})}</div>}
    </Card>

    <Dialog open={createOpen} title="Novo acerto pessoal" description="Cadastre a pessoa e o primeiro item do acerto." onClose={()=>setCreateOpen(false)}><form className="personal-settlements-v3__form" onSubmit={submitCreate}><Input label="Pessoa" value={personName} onChange={e=>setPersonName(e.target.value)} required/><Select label="Tipo" value={direction} onChange={e=>setDirection(e.target.value as PersonalSettlementDirection)} options={[{value:'owes_me',label:'A pessoa me deve'},{value:'i_owe',label:'Eu devo'}]}/><Input label="Data de início" type="date" value={startedOn} onChange={e=>setStartedOn(e.target.value)} required/><Input label="Descrição" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: empréstimo, compra, adiantamento"/><MoneyInput label="Valor" value={amount} onValueChange={setAmount} required/><Select label="Conta / banco" value={accountId} onChange={e=>setAccountId(e.target.value)} options={accountOptions} hint="Opcional. Se selecionada, a movimentação entra no saldo bancário."/><Input label="Observação" value={notes} onChange={e=>setNotes(e.target.value)}/><div className="personal-settlements-v3__form-actions"><Button variant="secondary" onClick={()=>setCreateOpen(false)}>Cancelar</Button><Button type="submit" loading={saving}>Salvar acerto</Button></div></form></Dialog>

    <Dialog open={itemTarget!==null} title={editingItem?'Editar item':'Adicionar item'} description={itemTarget?`Acerto com ${itemTarget.personName}`:undefined} onClose={()=>{setItemTarget(null);setEditingItem(null);}}><form className="personal-settlements-v3__form" onSubmit={submitItem}><Input label="Data" type="date" value={itemDate} onChange={e=>setItemDate(e.target.value)} required/><Input label="Descrição" value={itemDescription} onChange={e=>setItemDescription(e.target.value)} required/><MoneyInput label="Valor" value={itemAmount} onValueChange={setItemAmount} required/><Select label="Conta / banco" value={itemAccountId} onChange={e=>setItemAccountId(e.target.value)} options={accountOptions} hint="Opcional. Remover a conta ao editar remove também o lançamento financeiro vinculado."/><Input label="Observação" value={itemNotes} onChange={e=>setItemNotes(e.target.value)}/>{editingItem&&<Button variant="danger" onClick={()=>{setItemTarget(null);setEditingItem(null);setDeleteTarget({kind:'item',id:editingItem.id,label:editingItem.description});}}>Excluir item</Button>}<div className="personal-settlements-v3__form-actions"><Button variant="secondary" onClick={()=>{setItemTarget(null);setEditingItem(null);}}>Cancelar</Button><Button type="submit" loading={saving}>{editingItem?'Atualizar item':'Adicionar item'}</Button></div></form></Dialog>

    <Dialog open={movementTarget!==null} title={editingMovement?'Editar pagamento/recebimento':movementTarget?.direction==='i_owe'?'Registrar pagamento':'Registrar recebimento'} description={movementTarget?`${movementTarget.personName} · saldo ${currency.format(summary(movementTarget).balance)}`:undefined} onClose={()=>{setMovementTarget(null);setEditingMovement(null);}}><form className="personal-settlements-v3__form" onSubmit={submitMovement}><Input label="Data" type="date" max={localToday()} value={movementDate} onChange={e=>setMovementDate(e.target.value)} required/><MoneyInput label="Valor" value={movementAmount} onValueChange={setMovementAmount} required/><Select label="Conta / banco" value={movementAccountId} onChange={e=>setMovementAccountId(e.target.value)} options={requiredAccountOptions} hint="Obrigatória: o pagamento/recebimento atualiza o saldo real da conta."/><Input label="Observação" value={movementNote} onChange={e=>setMovementNote(e.target.value)}/>{editingMovement&&<Button variant="danger" onClick={()=>{setMovementTarget(null);setEditingMovement(null);setDeleteTarget({kind:'movement',id:editingMovement.id,label:'pagamento/recebimento'});}}>Excluir lançamento</Button>}<div className="personal-settlements-v3__form-actions"><Button variant="secondary" onClick={()=>{setMovementTarget(null);setEditingMovement(null);}}>Cancelar</Button><Button type="submit" loading={saving}>{editingMovement?'Atualizar':'Confirmar'}</Button></div></form></Dialog>

    <Dialog open={selected!==null} title={selected?.personName??'Acerto'} description={selected?selected.direction==='i_owe'?'Valor que eu devo':'Valor que devem para mim':undefined} onClose={()=>setDetailId(null)}>{selected&&<div className="personal-settlements-v3__detail"><div className="personal-settlements-v3__detail-kpis"><span>Total<strong>{currency.format(summary(selected).total)}</strong></span><span>Abatido<strong>{currency.format(summary(selected).paid)}</strong></span><span>Saldo<strong>{currency.format(summary(selected).balance)}</strong></span></div><div className="personal-settlements-v3__detail-head"><h3>Itens</h3><Button size="sm" onClick={()=>{setDetailId(null);openAddItem(selected);}}>＋ Adicionar</Button></div><div className="personal-settlements-v3__history">{rowItems(selected.id).map(item=><div key={item.id}><span><strong>{item.description}</strong><small>{dateLabel(item.itemDate)}{item.notes?` · ${item.notes}`:''}</small></span><span><b>{currency.format(item.amount)}</b><Button size="sm" variant="tertiary" onClick={()=>openEditItem(selected,item)}>Editar</Button></span></div>)}</div><div className="personal-settlements-v3__detail-head"><h3>Pagamentos / recebimentos</h3>{summary(selected).balance>0&&<Button size="sm" onClick={()=>{setDetailId(null);openAddMovement(selected);}}>＋ Registrar</Button>}</div><div className="personal-settlements-v3__history">{rowMovements(selected.id).length===0?<p className="ui-muted">Nenhum abatimento registrado.</p>:rowMovements(selected.id).map(move=><div key={move.id}><span><strong>{selected.direction==='i_owe'?'Pagamento':'Recebimento'}</strong><small>{dateLabel(move.movementDate)}{move.note?` · ${move.note}`:''}</small></span><span><b>{currency.format(move.amount)}</b><Button size="sm" variant="tertiary" onClick={()=>openEditMovement(selected,move)}>Editar</Button></span></div>)}</div></div>}</Dialog>

    <Dialog open={deleteTarget!==null} title="Confirmar exclusão" description={deleteTarget?.kind==='settlement'?'O controle particular será apagado, mas o histórico bancário já realizado será preservado.':'A movimentação financeira vinculada também será removida e os saldos serão recalculados.'} onClose={()=>setDeleteTarget(null)} footer={<><Button variant="secondary" onClick={()=>setDeleteTarget(null)}>Cancelar</Button><Button variant="danger" loading={saving} onClick={()=>void confirmDelete()}>Excluir</Button></>}>{deleteTarget&&<p>Excluir <strong>{deleteTarget.label}</strong>?</p>}</Dialog>
  </section>;
}
