from pathlib import Path

path = Path('src/modules/engineering/ui/EngineeringContractWorkspace.tsx')
s = path.read_text()

replacements = [
("type AllocationEdit={contractServiceId:string;structureId:string;serviceLabel:string;structureLabel:string;unit:string;quantity:string;maxQuantity:number;notes:string;availableFloors:string[];selectedFloors:string[];unitsPerFloor:number}|null;",
 "type AllocationEdit={contractServiceId:string;structureId:string;serviceLabel:string;structureLabel:string;unit:string;quantity:string;maxQuantity:number;notes:string;availableFloors:string[];selectedFloors:string[];unitsPerFloor:number;floorUnits:Record<string,number>}|null;"),
("function towerConfig(metadata:Record<string,unknown>|null|undefined){const raw=metadata?.towerConfig;if(!raw||typeof raw!=='object')return null;const cfg=raw as Record<string,unknown>;const floorCount=Number(cfg.floorCount);const unitsPerFloor=Number(cfg.unitsPerFloor);const firstFloor=Number(cfg.firstFloor??1);return Number.isFinite(floorCount)&&floorCount>0&&Number.isFinite(unitsPerFloor)&&unitsPerFloor>0?{floorCount,unitsPerFloor,firstFloor}:null;}",
 "function towerConfig(metadata:Record<string,unknown>|null|undefined){const raw=metadata?.towerConfig;if(!raw||typeof raw!=='object')return null;const cfg=raw as Record<string,unknown>;const floorCount=Number(cfg.floorCount);const unitsPerFloor=Number(cfg.unitsPerFloor);const firstFloor=Number(cfg.firstFloor??1);const hasGroundFloor=Boolean(cfg.hasGroundFloor??false);const groundFloorUnits=Math.max(0,Number(cfg.groundFloorUnits)||0);const hasRoof=Boolean(cfg.hasRoof??false);const roofUnits=Math.max(0,Number(cfg.roofUnits)||0);const totalUnits=Math.max(0,Number(cfg.totalUnits)||0);return Number.isFinite(floorCount)&&floorCount>0&&Number.isFinite(unitsPerFloor)&&unitsPerFloor>0?{floorCount,unitsPerFloor,firstFloor,hasGroundFloor,groundFloorUnits,hasRoof,roofUnits,totalUnits}:null;}"),
("      const floors=[...allocationEdit.selectedFloors].sort((a,b)=>Number(a)-Number(b));\n      const totalTowerCapacity=allocationEdit.availableFloors.length*allocationEdit.unitsPerFloor;\n      await operations.allocateContractService({workId,contractServiceId:allocationEdit.contractServiceId,structureId:allocationEdit.structureId,quantity:nextQuantity,notes:allocationEdit.notes||null,scopeConfig:allocationEdit.availableFloors.length?{active:floors.length>0,startFloor:floors.length?Number(floors[0]):null,floors,units:[],scopeQuantity:nextQuantity,outsideQuantity:Math.max(0,totalTowerCapacity-nextQuantity)}:null});",
 "      const floorRank=(floor:string)=>floor==='TR'?-1000000:floor==='COB'?1000000:Number(floor);\n      const floors=[...allocationEdit.selectedFloors].sort((a,b)=>floorRank(a)-floorRank(b));\n      const totalTowerCapacity=allocationEdit.availableFloors.reduce((sum,floor)=>sum+(allocationEdit.floorUnits[floor]??allocationEdit.unitsPerFloor),0);\n      const firstNumericFloor=floors.find(floor=>/^\\d+$/.test(floor));\n      await operations.allocateContractService({workId,contractServiceId:allocationEdit.contractServiceId,structureId:allocationEdit.structureId,quantity:nextQuantity,notes:allocationEdit.notes||null,scopeConfig:allocationEdit.availableFloors.length?{active:floors.length>0,startFloor:firstNumericFloor?Number(firstNumericFloor):null,floors,units:[],scopeQuantity:nextQuantity,outsideQuantity:Math.max(0,totalTowerCapacity-nextQuantity)}:null});"),
("  function toggleAllocationFloor(floor:string){setAllocationError(null);setAllocationEdit(current=>{if(!current)return current;const selected=current.selectedFloors.includes(floor)?current.selectedFloors.filter(item=>item!==floor):[...current.selectedFloors,floor];const derived=current.unit.trim().toLocaleUpperCase('pt-BR')==='APTO'&&current.unitsPerFloor>0?selected.length*current.unitsPerFloor:numberValue(current.quantity);return {...current,selectedFloors:selected,quantity:String(derived)};});}",
 "  function toggleAllocationFloor(floor:string){setAllocationError(null);setAllocationEdit(current=>{if(!current)return current;const selected=current.selectedFloors.includes(floor)?current.selectedFloors.filter(item=>item!==floor):[...current.selectedFloors,floor];const derived=current.unit.trim().toLocaleUpperCase('pt-BR')==='APTO'&&current.unitsPerFloor>0?selected.reduce((sum,item)=>sum+(current.floorUnits[item]??current.unitsPerFloor),0):numberValue(current.quantity);return {...current,selectedFloors:selected,quantity:String(derived)};});}"),
("const availableFloors=cfg?Array.from({length:cfg.floorCount},(_,offset)=>String(cfg.firstFloor+offset)):[];const savedFloors=Array.isArray(row.allocation.scopeConfig?.floors)?row.allocation.scopeConfig.floors.map(String):[];setAllocationError(null);setAllocationEdit({contractServiceId:row.service.id,structureId:selectedStructure.id,serviceLabel:row.service.description,structureLabel:selectedStructure.name,unit:row.service.unit,quantity:String(row.allocation.allocatedQuantity),maxQuantity:row.service.quantity,notes:row.allocation.notes??'',availableFloors,selectedFloors:savedFloors,unitsPerFloor:cfg?.unitsPerFloor??0});",
 "const availableFloors=cfg?[...(cfg.hasGroundFloor&&cfg.groundFloorUnits>0?['TR']:[]),...Array.from({length:cfg.floorCount},(_,offset)=>String(cfg.firstFloor+offset)),...(cfg.hasRoof&&cfg.roofUnits>0?['COB']:[])]:[];const floorUnits:Record<string,number>={};if(cfg){if(cfg.hasGroundFloor&&cfg.groundFloorUnits>0)floorUnits.TR=cfg.groundFloorUnits;Array.from({length:cfg.floorCount},(_,offset)=>String(cfg.firstFloor+offset)).forEach(floor=>{floorUnits[floor]=cfg.unitsPerFloor;});if(cfg.hasRoof&&cfg.roofUnits>0)floorUnits.COB=cfg.roofUnits;}const savedFloors=Array.isArray(row.allocation.scopeConfig?.floors)?row.allocation.scopeConfig.floors.map(String):[];setAllocationError(null);setAllocationEdit({contractServiceId:row.service.id,structureId:selectedStructure.id,serviceLabel:row.service.description,structureLabel:selectedStructure.name,unit:row.service.unit,quantity:String(row.allocation.allocatedQuantity),maxQuantity:row.service.quantity,notes:row.allocation.notes??'',availableFloors,selectedFloors:savedFloors,unitsPerFloor:cfg?.unitsPerFloor??0,floorUnits});"),
("{allocationEdit.availableFloors.map(floor=><button key={floor} type=\"button\" className={allocationEdit.selectedFloors.includes(floor)?'is-selected':''} onClick={()=>toggleAllocationFloor(floor)}>{floor}º</button>)}</div>{allocationEdit.unit.trim().toLocaleUpperCase('pt-BR')==='APTO'&&allocationEdit.unitsPerFloor>0&&<small>{allocationEdit.selectedFloors.length} pavimento(s) × {allocationEdit.unitsPerFloor} aptos = {quantity.format(numberValue(allocationEdit.quantity))} · quantitativo anterior {quantity.format(allocationEdit.maxQuantity)}</small>}",
 "{allocationEdit.availableFloors.map(floor=><button key={floor} type=\"button\" className={allocationEdit.selectedFloors.includes(floor)?'is-selected':''} onClick={()=>toggleAllocationFloor(floor)}>{floor==='TR'?'Térreo':floor==='COB'?'Cobertura':`${floor}º`}</button>)}</div>{allocationEdit.unit.trim().toLocaleUpperCase('pt-BR')==='APTO'&&allocationEdit.unitsPerFloor>0&&<small>{allocationEdit.selectedFloors.length} nível(is) selecionado(s) · {quantity.format(numberValue(allocationEdit.quantity))} aptos · capacidade da estrutura {quantity.format(allocationEdit.availableFloors.reduce((sum,floor)=>sum+(allocationEdit.floorUnits[floor]??allocationEdit.unitsPerFloor),0))}</small>}"),
]

for old,new in replacements:
    if old not in s:
        raise SystemExit('fragment not found:\n'+old[:220])
    s=s.replace(old,new,1)

path.write_text(s)
