begin;
create view public.projected_cash_flow with(security_invoker=true) as
with settlements as(
 select fe.tenant_id,fe.company_id,date_trunc('month',s.settled_on)::date competence,
 sum(case when fe.entry_type='income' then s.amount else 0 end)::numeric(18,2) actual_inflow,
 sum(case when fe.entry_type='expense' then s.amount else 0 end)::numeric(18,2) actual_outflow
 from public.financial_settlements s join public.financial_installments i on i.tenant_id=s.tenant_id and i.company_id=s.company_id and i.id=s.installment_id join public.financial_entries fe on fe.tenant_id=i.tenant_id and fe.company_id=i.company_id and fe.id=i.entry_id group by fe.tenant_id,fe.company_id,date_trunc('month',s.settled_on)::date),
open_titles as(
 select fe.tenant_id,fe.company_id,date_trunc('month',i.due_date)::date competence,
 sum(case when fe.entry_type='income' then greatest(i.amount-coalesce(x.paid,0),0) else 0 end)::numeric(18,2) open_inflow,
 sum(case when fe.entry_type='expense' then greatest(i.amount-coalesce(x.paid,0),0) else 0 end)::numeric(18,2) open_outflow
 from public.financial_installments i join public.financial_entries fe on fe.tenant_id=i.tenant_id and fe.company_id=i.company_id and fe.id=i.entry_id left join(select tenant_id,company_id,installment_id,sum(amount) paid from public.financial_settlements group by tenant_id,company_id,installment_id)x on x.tenant_id=i.tenant_id and x.company_id=i.company_id and x.installment_id=i.id group by fe.tenant_id,fe.company_id,date_trunc('month',i.due_date)::date),
eng_future as(select p.tenant_id,p.company_id,p.competence,sum(p.projected_amount)::numeric(18,2) engineering_projected_inflow from public.engineering_revenue_projections p where p.status='active' and not exists(select 1 from public.financial_entries fe where fe.tenant_id=p.tenant_id and fe.company_id=p.company_id and fe.engineering_contract_id=p.contract_id and fe.measurement_id is not null and fe.competence_month=p.competence) group by p.tenant_id,p.company_id,p.competence),
budget_exp as(select b.tenant_id,b.company_id,b.competence_month competence,sum(b.planned_amount)::numeric(18,2) budget_projected_outflow from public.budget_plans b where not exists(select 1 from public.financial_entries fe where fe.tenant_id=b.tenant_id and fe.company_id=b.company_id and fe.entry_type='expense' and fe.competence_month=b.competence_month and (b.cost_center_id is null or fe.cost_center_id=b.cost_center_id) and (b.category_id is null or fe.category_id=b.category_id)) group by b.tenant_id,b.company_id,b.competence_month),
keys as(select tenant_id,company_id,competence from settlements union select tenant_id,company_id,competence from open_titles union select tenant_id,company_id,competence from eng_future union select tenant_id,company_id,competence from budget_exp)
select k.tenant_id,k.company_id,k.competence,coalesce(s.actual_inflow,0)::numeric(18,2) actual_inflow,coalesce(s.actual_outflow,0)::numeric(18,2) actual_outflow,coalesce(o.open_inflow,0)::numeric(18,2) receivables_open,coalesce(o.open_outflow,0)::numeric(18,2) payables_open,coalesce(e.engineering_projected_inflow,0)::numeric(18,2) engineering_projected_inflow,coalesce(b.budget_projected_outflow,0)::numeric(18,2) budget_projected_outflow,(coalesce(s.actual_inflow,0)+coalesce(o.open_inflow,0)+coalesce(e.engineering_projected_inflow,0)-coalesce(s.actual_outflow,0)-coalesce(o.open_outflow,0)-coalesce(b.budget_projected_outflow,0))::numeric(18,2) projected_net_flow from keys k left join settlements s using(tenant_id,company_id,competence) left join open_titles o using(tenant_id,company_id,competence) left join eng_future e using(tenant_id,company_id,competence) left join budget_exp b using(tenant_id,company_id,competence);
commit;