begin;
-- Remove SELECT overlap caused by FOR ALL policies while preserving explicit SELECT policies.
drop policy if exists measurements_write on public.measurements;create policy measurements_insert on public.measurements for insert to authenticated with check(app_private.can_access_company(tenant_id,company_id));create policy measurements_update on public.measurements for update to authenticated using(app_private.can_access_company(tenant_id,company_id)) with check(app_private.can_access_company(tenant_id,company_id));create policy measurements_delete on public.measurements for delete to authenticated using(app_private.can_access_company(tenant_id,company_id));
drop policy if exists measurement_lines_write on public.measurement_lines;create policy measurement_lines_insert on public.measurement_lines for insert to authenticated with check(app_private.can_access_company(tenant_id,company_id));create policy measurement_lines_update on public.measurement_lines for update to authenticated using(app_private.can_access_company(tenant_id,company_id)) with check(app_private.can_access_company(tenant_id,company_id));create policy measurement_lines_delete on public.measurement_lines for delete to authenticated using(app_private.can_access_company(tenant_id,company_id));
drop policy if exists measurement_retentions_write on public.measurement_retentions;create policy measurement_retentions_insert on public.measurement_retentions for insert to authenticated with check(app_private.can_access_company(tenant_id,company_id));create policy measurement_retentions_update on public.measurement_retentions for update to authenticated using(app_private.can_access_company(tenant_id,company_id)) with check(app_private.can_access_company(tenant_id,company_id));create policy measurement_retentions_delete on public.measurement_retentions for delete to authenticated using(app_private.can_access_company(tenant_id,company_id));
drop policy if exists engineering_production_periods_write on public.engineering_production_periods;create policy engineering_production_periods_insert on public.engineering_production_periods for insert to authenticated with check(app_private.can_access_company(tenant_id,company_id));create policy engineering_production_periods_update on public.engineering_production_periods for update to authenticated using(app_private.can_access_company(tenant_id,company_id)) with check(app_private.can_access_company(tenant_id,company_id));create policy engineering_production_periods_delete on public.engineering_production_periods for delete to authenticated using(app_private.can_access_company(tenant_id,company_id));
drop policy if exists engineering_production_entries_write on public.engineering_production_entries;create policy engineering_production_entries_insert on public.engineering_production_entries for insert to authenticated with check(app_private.can_access_company(tenant_id,company_id));create policy engineering_production_entries_update on public.engineering_production_entries for update to authenticated using(app_private.can_access_company(tenant_id,company_id)) with check(app_private.can_access_company(tenant_id,company_id));create policy engineering_production_entries_delete on public.engineering_production_entries for delete to authenticated using(app_private.can_access_company(tenant_id,company_id));
-- Cover relevant Engineering FKs identified by performance advisor.
create index if not exists engineering_production_entries_service_fk_idx on public.engineering_production_entries(tenant_id,company_id,service_id);create index if not exists measurements_closed_by_idx on public.measurements(closed_by) where closed_by is not null;create index if not exists measurements_reopened_by_idx on public.measurements(reopened_by) where reopened_by is not null;create index if not exists measurement_reopen_actor_idx on public.measurement_reopen_log(actor_user_id) where actor_user_id is not null;create index if not exists engineering_production_periods_closed_by_idx on public.engineering_production_periods(closed_by) where closed_by is not null;create index if not exists engineering_production_periods_reopened_by_idx on public.engineering_production_periods(reopened_by) where reopened_by is not null;create index if not exists engineering_production_reopen_actor_idx on public.engineering_production_reopen_log(actor_user_id) where actor_user_id is not null;
commit;