begin;

create or replace function public.set_measurement_status(p_measurement_id uuid,p_action text,p_reason text default null) returns void language plpgsql security invoker set search_path='' as $$
declare v public.measurements%rowtype;
begin
 select * into v from public.measurements where id=p_measurement_id for update;
 if not found or not app_private.can_edit_company(v.tenant_id,v.company_id) then raise exception 'measurement not found or inaccessible';end if;
 if p_action='close' then if v.status<>'draft' then raise exception 'only draft can be closed';end if;update public.measurements set status='closed',closed_at=now(),closed_by=auth.uid() where id=v.id;
 elsif p_action='approve' then if v.status<>'closed' then raise exception 'only closed can be approved';end if;update public.measurements set status='approved' where id=v.id;
 elsif p_action='reopen' then if v.status not in('closed','approved') then raise exception 'only closed/approved can be reopened';end if;if nullif(trim(p_reason),'') is null then raise exception 'reopen reason is required';end if;if exists(select 1 from public.measurement_finance_links mfl where mfl.tenant_id=v.tenant_id and mfl.company_id=v.company_id and mfl.measurement_id=v.id) then raise exception 'measurement already linked to finance and cannot be reopened';end if;update public.measurements set status='draft',reopened_at=now(),reopened_by=auth.uid(),reopen_reason=p_reason where id=v.id;insert into public.measurement_reopen_log(tenant_id,company_id,measurement_id,reason,actor_user_id) values(v.tenant_id,v.company_id,v.id,p_reason,auth.uid());
 else raise exception 'invalid measurement action';end if;
end;$$;

create or replace function public.set_engineering_production_period_status(p_period_id uuid,p_action text,p_reason text default null) returns void language plpgsql security invoker set search_path='' as $$
declare v public.engineering_production_periods%rowtype;begin select * into v from public.engineering_production_periods where id=p_period_id for update;if not found or not app_private.can_edit_company(v.tenant_id,v.company_id) then raise exception 'production period not found or inaccessible';end if;if p_action='close' then if v.status<>'open' then raise exception 'only open period can be closed';end if;update public.engineering_production_periods set status='closed',closed_at=now(),closed_by=auth.uid() where id=v.id;elsif p_action='reopen' then if v.status<>'closed' then raise exception 'only closed period can be reopened';end if;if nullif(trim(p_reason),'') is null then raise exception 'reopen reason is required';end if;update public.engineering_production_periods set status='open',reopened_at=now(),reopened_by=auth.uid(),reopen_reason=p_reason where id=v.id;insert into public.engineering_production_reopen_log(tenant_id,company_id,production_period_id,reason,actor_user_id) values(v.tenant_id,v.company_id,v.id,p_reason,auth.uid());else raise exception 'invalid production action';end if;end;$$;

create or replace function public.generate_measurement_receivable(p_measurement_id uuid,p_due_date date) returns uuid language plpgsql security invoker set search_path='' as $$
declare v_m public.measurements%rowtype;v_contract public.engineering_contracts%rowtype;v_work public.works%rowtype;v_net numeric(18,2);v_entry uuid;v_installment uuid;v_existing uuid;begin if p_due_date is null then raise exception 'due date is required';end if;select * into v_m from public.measurements where id=p_measurement_id for update;if not found or not app_private.can_manage_company(v_m.tenant_id,v_m.company_id) then raise exception 'measurement not found or inaccessible';end if;if v_m.status<>'approved' then raise exception 'only approved measurements generate receivables';end if;select financial_entry_id into v_existing from public.measurement_finance_links where tenant_id=v_m.tenant_id and company_id=v_m.company_id and measurement_id=v_m.id;if found then return v_existing;end if;select * into v_contract from public.engineering_contracts where tenant_id=v_m.tenant_id and company_id=v_m.company_id and id=v_m.contract_id;select * into v_work from public.works where tenant_id=v_m.tenant_id and company_id=v_m.company_id and id=v_contract.work_id;select net_amount into v_net from public.measurement_financial_summary where measurement_id=v_m.id;if coalesce(v_net,0)<=0 then raise exception 'measurement net amount must be positive';end if;insert into public.financial_entries(tenant_id,company_id,entry_type,description,counterparty_name,competence_month,notes,created_by,work_id,engineering_contract_id,measurement_id) values(v_m.tenant_id,v_m.company_id,'income','Medição - '||coalesce(v_work.name,'Obra')||' - Contrato '||coalesce(v_contract.contract_number,'s/n'),coalesce(v_contract.client_name,v_work.client_name),v_m.competence,'Gerado automaticamente pela Engenharia. Medição: '||v_m.id::text,auth.uid(),v_work.id,v_contract.id,v_m.id) returning id into v_entry;insert into public.financial_installments(tenant_id,company_id,entry_id,installment_number,installment_count,due_date,amount,competence_month) values(v_m.tenant_id,v_m.company_id,v_entry,1,1,p_due_date,v_net,v_m.competence) returning id into v_installment;insert into public.measurement_finance_links(tenant_id,company_id,measurement_id,financial_entry_id,financial_installment_id,linked_by) values(v_m.tenant_id,v_m.company_id,v_m.id,v_entry,v_installment,auth.uid());return v_entry;end;$$;

create or replace function public.receive_measurement(p_measurement_id uuid,p_account_id uuid,p_received_on date,p_amount numeric default null) returns uuid language plpgsql security invoker set search_path='' as $$
declare v_m public.measurements%rowtype;v_link public.measurement_finance_links%rowtype;v_installment public.financial_installments%rowtype;v_account public.financial_accounts%rowtype;v_paid numeric(18,2);v_remaining numeric(18,2);v_receive numeric(18,2);v_settlement uuid;v_key text;begin if p_received_on is null then raise exception 'received date is required';end if;select * into v_m from public.measurements where id=p_measurement_id for update;if not found or not app_private.can_manage_company(v_m.tenant_id,v_m.company_id) then raise exception 'measurement not found or inaccessible';end if;select * into v_link from public.measurement_finance_links where tenant_id=v_m.tenant_id and company_id=v_m.company_id and measurement_id=v_m.id;if not found then raise exception 'measurement has no generated receivable';end if;select * into v_installment from public.financial_installments where tenant_id=v_m.tenant_id and company_id=v_m.company_id and id=v_link.financial_installment_id for update;select * into v_account from public.financial_accounts where tenant_id=v_m.tenant_id and company_id=v_m.company_id and id=p_account_id and status='active';if not found then raise exception 'active financial account not found in measurement company';end if;select coalesce(sum(amount),0) into v_paid from public.financial_settlements where tenant_id=v_m.tenant_id and company_id=v_m.company_id and installment_id=v_installment.id;v_remaining:=round(v_installment.amount-v_paid,2);if v_remaining<=0 then raise exception 'measurement receivable is already fully settled';end if;v_receive:=coalesce(p_amount,v_remaining);if v_receive<=0 or v_receive>v_remaining then raise exception 'received amount must be positive and cannot exceed remaining receivable';end if;v_key:='measurement-receipt:'||v_m.id::text||':'||(select count(*)+1 from public.financial_settlements where tenant_id=v_m.tenant_id and company_id=v_m.company_id and installment_id=v_installment.id)::text;insert into public.financial_settlements(tenant_id,company_id,installment_id,account_id,settled_on,amount,idempotency_key,notes,created_by) values(v_m.tenant_id,v_m.company_id,v_installment.id,p_account_id,p_received_on,v_receive,v_key,'Recebimento de medição da Engenharia: '||v_m.id::text,auth.uid()) returning id into v_settlement;return v_settlement;end;$$;

commit;
