import { useEffect, useMemo, useState } from 'react';
import { BarChart3, CalendarCheck, Clock3, FileText, FolderUp, HardHat, ReceiptText, ShieldCheck, Upload, UsersRound, WalletCards } from 'lucide-react';
import type { CompanySummary } from '../../platform/domain/AccessContext';
import type { HrOperationalSnapshot } from '../application/HrOperationsRepository';
import { getHrBudgetRepository, getHrOperationsRepository } from '../infrastructure/createHrRepositories';
import { Button } from '../../../shared/ui/Button';
import { Card } from '../../../shared/ui/Card';
import { Input } from '../../../shared/ui/Input';
import { SearchableSelect, type SearchableSelectOption } from '../../../shared/ui/SearchableSelect';
import { Select } from '../../../shared/ui/Select';
import { currentHrCompetence } from './useHrBudgetOverview';
import './hr-workspace.css';

type HrWorkspaceTab = 'dashboard' | 'colaboradores' | 'epis' | 'compliance' | 'salarios' | 'presenca' | 'banco_horas' | 'fechamento' | 'relatorios' | 'recibos' | 'importacoes' | 'documentos';
type CompanyData = { company: CompanySummary; operations: HrOperationalSnapshot; overview: Awaited<ReturnType<ReturnType<typeof getHrBudgetRepository>['getOverview']>>; };
const ALL_HR_COMPANIES = '__all_hr_companies__';
const tabs: Array<{ id: HrWorkspaceTab; label: string; icon: typeof BarChart3 }> = [
  { id:'dashboard',label:'Dashboard',icon:BarChart3 },{ id:'colaboradores',label:'Colaboradores',icon:UsersRound },{ id:'epis',label:'EPIs',icon:HardHat },{ id:'compliance',label:'ASO, NR e Férias',icon:ShieldCheck },{ id:'salarios',label:'Salários e pagamentos',icon:WalletCards },{ id:'presenca',label:'Presença e ponto',icon:CalendarCheck },{ id:'banco_horas',label:'Banco de horas',icon:Clock3 },{ id:'fechamento',label:'Fechamento quinzenal',icon:WalletCards },{ id:'relatorios',label:'Relatórios',icon:FileText },{ id:'recibos',label:'Recibos',icon:ReceiptText },{ id:'importacoes',label:'Importações',icon:Upload },{ id:'documentos',label:'Importações RH',icon:FolderUp },
];
const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
function companyLabel(company: CompanySummary): string { const raw=`${company.tradeName??''} ${company.legalName}`.toLocaleUpperCase('pt-BR'); if(raw.includes('PESSOAL'))return'Pessoal'; if(raw.includes('PR-HIST')||/(^|\s)PR(\s|$)/.test(raw))return'PR'; if(raw.includes('CR-HIST')||/(^|\s)CR(\s|$)/.test(raw))return'CR'; return company.tradeName??company.legalName; }
function normalizeSearch(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR').trim();}
function smartMatches(values:Array<string|null|undefined>,query:string){const q=normalizeSearch(query);if(!q)return true;const tokens=q.split(/\s+/).filter(Boolean);const searchable=normalizeSearch(values.filter(Boolean).join(' '));const words=searchable.split(/\s+/).filter(Boolean);return tokens.every(t=>words.some(w=>w.startsWith(t))||searchable.includes(t));}

export function HrWorkspacePage({companies,initialCompanyId}:{companies:readonly CompanySummary[];initialCompanyId?:string}){
 const [tab,setTab]=useState<HrWorkspaceTab>('dashboard'); const [competence,setCompetence]=useState(()=>currentHrCompetence().month.slice(0,7)); const [companyFilter,setCompanyFilter]=useState(()=>initialCompanyId&&companies.some(i=>i.id===initialCompanyId)?initialCompanyId:ALL_HR_COMPANIES); const [employeeSearch,setEmployeeSearch]=useState(''); const [employeeStatus,setEmployeeStatus]=useState('active'); const [companyData,setCompanyData]=useState<CompanyData[]>([]); const [loading,setLoading]=useState(false); const [errorMessage,setErrorMessage]=useState<string|null>(null); const competenceMonth=`${competence}-01`;
 useEffect(()=>{if(initialCompanyId&&companies.some(i=>i.id===initialCompanyId))setCompanyFilter(initialCompanyId);else if(initialCompanyId===undefined)setCompanyFilter(ALL_HR_COMPANIES);},[companies,initialCompanyId]);
 const visibleCompanies=useMemo(()=>companyFilter===ALL_HR_COMPANIES?companies:companies.filter(i=>i.id===companyFilter),[companies,companyFilter]);
 useEffect(()=>{let cancelled=false;const operationsRepository=getHrOperationsRepository();const budgetRepository=getHrBudgetRepository();setLoading(true);setErrorMessage(null);void Promise.all(visibleCompanies.map(async company=>{const scope={tenantId:company.tenantId,companyId:company.id};const [operations,overview]=await Promise.all([operationsRepository.getSnapshot(scope,competenceMonth),budgetRepository.getOverview({...scope,competenceMonth,year:Number(competenceMonth.slice(0,4))})]);return{company,operations,overview} satisfies CompanyData;})).then(data=>{if(!cancelled)setCompanyData(data);}).catch(()=>{if(!cancelled){setCompanyData([]);setErrorMessage('Não foi possível carregar os dados do RH para o filtro selecionado.');}}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[visibleCompanies,competenceMonth]);
 const employees=companyData.flatMap(({company,operations})=>operations.employees.map(item=>({...item,companyId:company.id,companyName:companyLabel(company)}))); const activeEmployees=employees.filter(i=>i.contractStatus==='active'); const filteredEmployees=employees.filter(item=>{if(employeeStatus!=='all'&&item.contractStatus!==employeeStatus)return false;return smartMatches([item.fullName,item.jobTitle,item.costCenterName,item.cpf,item.sector,item.companyName],employeeSearch);});
 const salaryPlanned=companyData.reduce((t,i)=>t+i.overview.salaryProjection.reduce((s,r)=>s+r.plannedSalary,0),0); const salaryRealized=companyData.reduce((t,i)=>t+i.overview.salaryProjection.reduce((s,r)=>s+r.realizedSalary,0),0); const works=new Set(activeEmployees.map(i=>`${i.companyId}:${i.costCenterId??''}`).filter(i=>!i.endsWith(':'))).size; const bankHours=activeEmployees.filter(i=>i.bankHoursEnabled).length; const eventTotal=companyData.reduce((t,i)=>t+i.operations.payrollEvents.filter(e=>e.status==='active').reduce((s,e)=>s+e.amount,0),0);
 const companyOptions=[...(companies.length>1?[{value:ALL_HR_COMPANIES,label:'Todas as empresas'}]:[]),...companies.map(c=>({value:c.id,label:companyLabel(c)}))]; const scopeLabel=companyFilter===ALL_HR_COMPANIES?'Todas as empresas':companyLabel(companies.find(i=>i.id===companyFilter)??companies[0]!); const employeeOptions:SearchableSelectOption[]=activeEmployees.map(item=>({value:item.employmentContractId,label:companyFilter===ALL_HR_COMPANIES?`${item.fullName} · ${item.companyName}`:item.fullName,keywords:[item.fullName,item.companyName,item.jobTitle,item.costCenterName??'',item.cpf??'',item.sector??'']})); const employeePicker=(label='Colaborador')=><SearchableSelect label={label} options={employeeOptions} placeholder="Digite o nome do colaborador"/>;
 return <section className="hr-workspace">
  <Card className="hr-workspace__hero" title="RH" actions={<Button size="sm" onClick={()=>setTab('colaboradores')}>＋ Novo colaborador</Button>}><div className="hr-workspace__top-filters"><Select label="Empresa" value={companyFilter} options={companyOptions} onChange={e=>setCompanyFilter(e.target.value)}/><Input label="Competência" type="month" value={competence} onChange={e=>setCompetence(e.target.value)}/></div></Card>
  <nav className="hr-workspace__tabs" aria-label="Módulos do RH">{tabs.map(({id,label,icon:Icon})=><button key={id} type="button" className={tab===id?'is-active':''} onClick={()=>setTab(id)}><Icon size={20}/><span>{label}</span></button>)}</nav>
  {loading&&<Card><p className="ui-muted">Carregando dados do RH...</p></Card>}{errorMessage&&<Card><p>{errorMessage}</p></Card>}
  {!loading&&!errorMessage&&tab==='dashboard'&&<div className="hr-workspace__content"><Card title="Painel financeiro do RH" description={`${activeEmployees.length} colaboradores ativos · ${scopeLabel}`}><div className="hr-workspace__primary-total"><span>Total da competência</span><strong>{money.format(salaryRealized)}</strong><small>Previsto {money.format(salaryPlanned)}</small></div></Card><div className="hr-workspace__kpis"><Card title="Colaboradores ativos"><strong>{activeEmployees.length}</strong><span className="ui-muted">Base disponível para lançamentos</span></Card><Card title="Pagamentos"><strong>{money.format(salaryRealized)}</strong><span className="ui-muted">Competência atual</span></Card><Card title="Extras e reembolsos"><strong>{money.format(eventTotal)}</strong><span className="ui-muted">Eventos ativos</span></Card><Card title="Média por colaborador"><strong>{money.format(activeEmployees.length?salaryRealized/activeEmployees.length:0)}</strong><span className="ui-muted">Valor realizado</span></Card></div></div>}
  {!loading&&!errorMessage&&tab==='colaboradores'&&<div className="hr-workspace__content"><Card title="Colaboradores"><div className="hr-workspace__kpis hr-workspace__kpis--small"><Card title="Total"><strong>{employees.length}</strong></Card><Card title="Ativos"><strong>{activeEmployees.length}</strong></Card><Card title="Obras"><strong>{works}</strong></Card><Card title="Banco de horas"><strong>{bankHours}</strong></Card></div></Card><Card><div className="hr-workspace__filters"><Input label="Buscar colaborador" placeholder="Digite nome, CPF, empresa ou obra" value={employeeSearch} onChange={e=>setEmployeeSearch(e.target.value)}/><Select label="Status" value={employeeStatus} onChange={e=>setEmployeeStatus(e.target.value)} options={[{value:'active',label:'Ativos'},{value:'terminated',label:'Desligados'},{value:'all',label:'Todos'}]}/></div>{filteredEmployees.length===0?<p className="ui-muted">Nenhum colaborador encontrado.</p>:<div className="hr-workspace__list">{filteredEmployees.map(item=><div key={`${item.companyId}:${item.employmentContractId}`}><div><strong>{item.fullName}</strong><span>{item.companyName} · {item.jobTitle} · {item.costCenterName??'Sem obra'}</span></div><div><strong>{money.format(item.baseSalary)}</strong><span>{item.contractStatus==='active'?'Ativo':'Desligado'}</span></div></div>)}</div>}</Card></div>}
  {!loading&&!errorMessage&&tab==='epis'&&<div className="hr-workspace__content"><div className="hr-workspace__quick-three"><Card title="Histórico de entregas"><Clock3/></Card><Card title="Cadastro de EPIs"><HardHat/></Card><Card title="Fichas de EPIs"><FolderUp/></Card></div><Card title="Entrega de EPI"><div className="hr-workspace__form">{employeePicker()}<Input label="EPI" placeholder="Selecione ou informe o EPI"/><Input label="Quantidade" type="number" min="1" defaultValue="1"/><Input label="Data da entrega" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><Button>Registrar entrega</Button></div></Card></div>}
  {!loading&&!errorMessage&&tab==='compliance'&&<div className="hr-workspace__content"><Card title="Saúde, segurança e férias" actions={<Button>＋ Novo registro</Button>}><div className="hr-workspace__segment"><Button variant="secondary">ASO</Button><Button variant="secondary">NRs e treinamentos</Button><Button variant="secondary">Férias</Button></div><div className="hr-workspace__empty">Nenhum registro nesta área.</div></Card></div>}
  {!loading&&!errorMessage&&tab==='salarios'&&<div className="hr-workspace__content"><Card title="Salário e Contas a Pagar"><div className="hr-workspace__form">{employeePicker()}<Input label="Salário / valor" value={salaryPlanned?String(salaryPlanned):''} readOnly/><div className="hr-workspace__actions"><Button>Gerar pagamento</Button><Button variant="secondary">Configurar encargos</Button></div></div></Card></div>}
  {!loading&&!errorMessage&&tab==='presenca'&&<div className="hr-workspace__content"><Card title="Presença e ponto" actions={<Button variant="secondary">Registrados</Button>}><div className="hr-workspace__form"><Input label="Data" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><Button>Marcar todos presentes</Button><Button variant="secondary">PDF empresa</Button>{employeePicker('Relatório individual')}</div></Card></div>}
  {!loading&&!errorMessage&&tab==='banco_horas'&&<div className="hr-workspace__content"><Card title="Banco de horas"><div className="hr-workspace__form">{employeePicker()}<div className="hr-workspace__actions"><Button>Registrar movimento</Button><Button variant="secondary">Fechar competência</Button></div></div></Card></div>}
  {!loading&&!errorMessage&&tab==='fechamento'&&<div className="hr-workspace__content"><Card title="Fechamento quinzenal"><div className="hr-workspace__form"><Select label="Quinzena" options={[{value:'1',label:'1ª quinzena'},{value:'2',label:'2ª quinzena'}]}/>{employeePicker()}<div className="hr-workspace__actions"><Button>Apurar</Button><Button variant="secondary">Fechar quinzena</Button></div></div></Card></div>}
  {!loading&&!errorMessage&&tab==='relatorios'&&<div className="hr-workspace__content"><Card title="Relatórios do RH"><div className="hr-workspace__form"><Select label="Modelo" options={[{value:'detalhado',label:'Relatório detalhado por colaborador'},{value:'consolidado',label:'Consolidado por empresa'},{value:'banco',label:'Banco de horas'}]}/><Input label="Competência inicial" type="month" value={competence} onChange={e=>setCompetence(e.target.value)}/><Input label="Competência final" type="month" value={competence} readOnly/><Button>Gerar relatório</Button></div></Card></div>}
  {!loading&&!errorMessage&&tab==='recibos'&&<div className="hr-workspace__content"><Card title="Recibos" description="Selecione colaborador e verbas para gerar ou imprimir."><div className="hr-workspace__form"><Select label="Quinzena" options={[{value:'all',label:'Todas'},{value:'1',label:'1ª quinzena'},{value:'2',label:'2ª quinzena'}]}/>{employeePicker()}<div className="hr-workspace__actions"><Button>Gerar recibo</Button><Button variant="secondary">Imprimir</Button></div></div></Card></div>}
  {!loading&&!errorMessage&&tab==='importacoes'&&<div className="hr-workspace__content"><Card title="Importação" description="Modelos CSV separados por ponto e vírgula."><div className="hr-workspace__upload"><label>Importar colaboradores<input type="file" accept=".csv,text/csv"/></label><label>Importar fechamento quinzenal<input type="file" accept=".csv,text/csv"/></label><label>Importar banco de horas<input type="file" accept=".csv,text/csv"/></label></div></Card></div>}
  {!loading&&!errorMessage&&tab==='documentos'&&<div className="hr-workspace__content"><Card title="Importações RH" description="Holerites e documentos separados por módulo"><div className="hr-workspace__form"><label className="hr-workspace__file">Escolher arquivo<input type="file"/></label><Button>Importar documento RH</Button><p className="ui-muted">Nenhum documento RH importado.</p></div></Card></div>}
 </section>;
}
